### ISSUE TITLE
dynamic ref bug

### ISSUE THREAD

**Issue by mioe** [YvesCoding/vuescroll#100]
https://codesandbox.io/s/xpzr65yj44
Need to scroll down after switching to another dialog, `scrollTo` works after pressing user again.
![2wsas6nifj](https://user-images.githubusercontent.com/16230771/52090398-50bda600-25c2-11e9-9bdb-531546a56a40.gif)

**Comment by wangyi7099** [comment]
Hi, you can solve thi by give a default value to `selectedUser`
```javascript
{
  selectedUser: 1
}
```

And use `scrollTo` api in `setTimeout`.
```javascript
scrollTo2(id) {
      let ref_this = "scroll" + id;
      console.log(this.$refs);
      setTimeout(() => {
        this.$refs[ref_this][0].scrollTo(
          {
            x: 0,
            y: "110%"
          },
          true
        );
      }, 0);
    }
```

Using marcro task such as `setTimeout` can make sure **scrollTo works after Vue  diff/patch**.

**Comment by mioe** [comment]
thanks 😉

**Comment by wangyi7099** [comment]
Yes, all right. Maybe nextTick is enough. But        
 nextTick would always use micro task that 
is a little short and sometimes cannot make sure being triggered after dom finishes updating completely.
