### ISSUE TITLE
Blurry border

### ISSUE THREAD

**Issue by GitNomster** [YvesCoding/vuescroll#101]
When i scrolling down sometimes top and bottom side border become blurry. And it changing upon all way of rail. Horizontal line has same effect.
I'm using Win 10 chrome 72.0.3626.96.
[Link to repro](https://jsfiddle.net/4pgcre0f/7/)
![Example](https://user-images.githubusercontent.com/29253035/52407482-3e77c680-2af2-11e9-8901-d371d148cd05.png)

**Comment by wangyi7099** [comment]
I cannot connect to  `jsfiddle` , could you please change a place to put your code ? Such as codepen, codesandbox...

**Comment by GitNomster** [comment]
[Codepen](https://codepen.io/anon/pen/aXVxdz)

**Comment by wangyi7099** [comment]
I can't see the blurry border both on codepen and  your screenshot...  Can you increase the border value and decrease the bar's size ti make border more clear?

I'm suing win10 and chrome 72 too.

**Comment by GitNomster** [comment]
Here is another example [link](https://codepen.io/anon/pen/aXVxdz) and some pics.
Left clear - right blurry.
![image](https://user-images.githubusercontent.com/29253035/52459999-1f2c7800-2b8a-11e9-9bb2-b18abdcb3347.png)

**Comment by wangyi7099** [comment]
Thanks for the report! I will reply to you tomorrow.

**Comment by wangyi7099** [comment]
Still didn't see blurry border in my computer. Does someone else see the blurry border in the code example above?

**Comment by GitNomster** [comment]
Look here. When I scroll, sometimes it gets blurry, and sometimes it doesn't.
![test](https://user-images.githubusercontent.com/29253035/52546843-5302da00-2de4-11e9-8f9a-ce33c680d835.gif)

**Comment by wangyi7099** [comment]
It's not obviouse. I still cannot see the blurry border,

**Comment by GitNomster** [comment]
This blur disappears if you use position instead of transform.
