### ISSUE TITLE
Browser scrollbar is visible in 4.10.4

### ISSUE THREAD

**Issue by pytkin** [YvesCoding/vuescroll#102]
Browser scrollbar is visible on Mac OS, in latest Chrome/Firefox/Safari: https://cl.ly/8e29a5898f8d

I didn't see this issue in 4.9.6.

**Comment by wangyi7099** [comment]
4.10.5 has been released and fixed this issue.

**Comment by pytkin** [comment]
@wangyi7099 how about Firefox? https://cl.ly/c097e89a5f1f

**Comment by wangyi7099** [comment]
Works well on filrefox.

**Comment by wangyi7099** [comment]
works well on Firefox .  BTW, I couldn't see your video

**Comment by wangyi7099** [comment]
OK I got it. Fix one issue will fix all issues of them. They have the same issue in previous 4.10.x version. Thanks for the report!

**Comment by pytkin** [comment]
Ok, thank you!
