### ISSUE TITLE
How to toggle with the mode of  'slide' and 'native' ?

### ISSUE THREAD

**Issue by tingshuai** [YvesCoding/vuescroll#104]
As title ,and I have tryed to use api of refresh and load etc . but it does'nt work;
Is there any way to toggle it ?

**Comment by wangyi7099** [comment]
https://vuescrolljs.yvescoding.org/guide/configuration.html#mode

**Comment by sebenik** [comment]
I think the question was how to toggle the mode once the scroller has been initialized.
Is there a way to toggle the mode dynamically with computed properties?

It seems some properties are reactive (e.g. color of the bar) but changing mode options on already initialized vue-scroll component doesn't seem to work.
