### ISSUE TITLE
当滚动内容超长时，滚动bar宽度很小，难以拖动

### ISSUE THREAD

**Issue by sally2015** [YvesCoding/vuescroll#108]
![image](https://user-images.githubusercontent.com/14807468/53325205-b846e700-391d-11e9-9789-0e1c870d01f2.png)
如题，我尝试加了min-width，但是好像影响了计算

**Comment by wangyi7099** [comment]
https://vuescrolljs.yvescoding.org/guide/configuration.html#minsize
