### ISSUE TITLE
外层嵌套vuescroll后内部的原始scroll无法用鼠标中键滚动

### ISSUE THREAD

**Issue by luoxiaoji** [YvesCoding/vuescroll#109]
win10,
vue + antd + vuescroll(最新).

==================

事情是这样的，

我在antd Modal 里有一个vuescroll滚动条，滚动条内 有一个富文本，但是富文本用的是原始scroll.

在富文本里写完长文本后 无法用鼠标中键滚动 ，鼠标中键滚动反而会触发 外层 Modal的滚动条。 只能拖动。

可能是我使用的方法问题，但是在网上实在没有找到靠谱的解决办法，所以只能在这请教下是什么原因导致的？

**Comment by wangyi7099** [comment]
麻烦把**能重现次bug的demo**放到GitHub上，我下载下来运行查看一下

**Comment by luoxiaoji** [comment]
多谢回复，我单摘出来一个。  -> [地址](https://github.com/luoxiaoji/testDemo.git) 

由于用了 跨平台的eletron 所以会稍微有点大。

**Comment by wangyi7099** [comment]
好的，谢谢你的demo，我去查看一下，现在手头还有点别的事，可能需要过两天才能回复。

**Comment by luoxiaoji** [comment]
> 好的，谢谢你的demo，我去查看一下，现在手头还有点别的事，可能需要过两天才能回复。

麻烦您了，我并不是特别着急，况且这个很可能和vuescroll 没有关系。

**Comment by xiaocoati** [comment]
同求这个问题的解决方法啊，我也遇到这个问题

**Comment by wangyi7099** [comment]
今晚发布个`4.11.2`  再试试行不行

**Comment by luoxiaoji** [comment]
好的，坐等~

**Comment by luoxiaoji** [comment]
> 今晚发布个`4.11.2` 再试试行不行

其中还有另外一个问题之前忘了询问了，就是无论高度设置的足够，总会有一小节可以滑动。查了半天样式不明所以

**Comment by wangyi7099** [comment]
可能是 `margin` 之类的影响内容的高度了。 不会无缘无故产生滚动条的，肯定是内容超了

**Comment by luoxiaoji** [comment]
> 可能是 `margin` 之类的影响内容的高度了。 不会无缘无故产生滚动条的，肯定是内容超了

老哥厉害，的确是margin影响，底子差，不知道为什么，每行的margin上下各空出了10px,加起来实际远远没有超过高度，但是全部改成 padding 就可以了。

**Comment by wangyi7099** [comment]
4.11.2 今晚发不了了 不好意思。。。  因为slide模式出了一个bug 我需要一起修复 然后发布版本。

**Comment by xiaocoati** [comment]
太厉害了，下了4.11.2版本果然可以了，赞赞赞 @
