### ISSUE TITLE
Smoothing

### ISSUE THREAD

**Issue by GitNomster** [YvesCoding/vuescroll#110]
In vuescroll v. 4.11.1 mousescrolling stopped going smoothly. How to make it like in 4.10.5?

**Comment by wangyi7099** [comment]
https://vuescrolljs.yvescoding.org/guide/configuration.html#wheelscrollduration

**Comment by GitNomster** [comment]
There is no wheelscrollduration option in docs.

**Comment by wangyi7099** [comment]
You have cache in your browser, please clean it and try again

**Comment by GitNomster** [comment]
It was much better without wheelscrollduration.
