### ISSUE TITLE
Detect if scrollbar is visibile

### ISSUE THREAD

**Issue by kaiserkiwi** [YvesCoding/vuescroll#112]
Hi there,

probably I miss something, but am I right, that there is no clean way to find out, if the scrollbar is visible?

I know I can access it with `.__vuescroll .__panel[style*='overflow: hidden scroll']` but when the Package changes some day it could break everything. I think it would be a much cleaner way to gibt `.__vuescroll` an extra class like `.has-scrollbar` or `.scrollbar-visible`. This would make CSS based on the visibility of the scrollbar so much cleaner.

**Comment by wangyi7099** [comment]
thanks for your suggestion, I will ship it in next release.

**Comment by wemod123** [comment]
Is this issue still valid?
since I'm also seeking for this feature, hasn't found in documents etc...

**Comment by wangyi7099** [comment]
Yes, this feature is called `class hook`  . You can find it in the doc.

**Comment by wemod123** [comment]
Highly appreciate your quick reply, amazing hooks!
