### ISSUE TITLE
Unable to scroll by max-height

### ISSUE THREAD

**Issue by trandaison** [YvesCoding/vuescroll#113]
Is there any way to set the `max-height` property for the parent instead of fixing a `height`?

Here I have an example. Try to change the data `mode: 'max-height'` by default, it doesn't work at all. 

But it works if I set the `height` by default; and then switch to `max-height` and resize the window a little bit it's not working any more.

https://jsfiddle.net/sontd/zgvrq89u/3/

**Comment by wangyi7099** [comment]
Could you plz put the code on codepen? I'm sorry I cannot connect to jsfiddle.

**Comment by trandaison** [comment]
Here it is:
https://codepen.io/sontd/pen/zXxVJv

Line 5, set the data to `height` and `max-height` manually to see the results.

**Comment by wangyi7099** [comment]
Add ` position: relative;` to parent dom.

**Comment by trandaison** [comment]
Oh, It worked! I think this should be mentioned in the documentation.

Thank you!

**Comment by trandaison** [comment]
Oh, I think it didn't work properly, just like the component wasn't destroyed and recreate, it was updated after changing the code.

To make sure, please add `position: relative;` to parent dom, change the mode to `mode: 'height'`, then turn it back `mode: 'max-height'` you will see.

**Comment by wangyi7099** [comment]
try 4.12.0

**Comment by TimYi** [comment]
This bug is not resolved under 4.13.1.

**Comment by sebenik** [comment]
Can we reopen this?

**Comment by borovez** [comment]
> I cannot get maxHeight to work either, it is driving me nuts...
> 
> My vuscroll version is **4.16.1**
> 
> My vue component template:
> 
> ```
> <div class="relative overflow-auto">
>     <vuescroll :ops="ops">
>         <slot name="content" />
>    </vuescroll>
> </div>
> ```
> 
> My options are set as:
> 
> ```
> ops: {
>     maxHeight:200,
>     vuescroll: {
>         sizeStrategy: 'number',
>     },
> }
> ```
