### ISSUE TITLE
Rendering child component with vuescroll causing app re-render in iphones

### ISSUE THREAD

**Issue by Solomka12** [YvesCoding/vuescroll#116]
When I display child component which has vuescroll with `v-if` my parent `App.vue` re-renders.
This problem only occurs in iPhones (mobile safari & chrome)

**Comment by wangyi7099** [comment]
Can you provide a minimalistic repo that can reproduce this issue?

**Comment by Solomka12** [comment]
@wangyi7099 
here is jsfiddle: [https://jsfiddle.net/Solomka/0d2ykuvh/4/](https://jsfiddle.net/Solomka/0d2ykuvh/4/)

Just test it with any apple device (iphone/ipad)
You can also test it in chrome devtools with device emulator. It works same in this case.

Toggling the list with vue-scroll in it re-renders application.
You can see it in devtools console after each list display.

**Comment by wangyi7099** [comment]
Can you put it on other places rather than jsfiddle ?   I'm sorry I cannot connect to jsfiddle

**Comment by Solomka12** [comment]
Yeah, sure
[https://codepen.io/Solomka/pen/xebwrV](https://codepen.io/Solomka/pen/xebwrV)
