### ISSUE TITLE
4.12.0的Slide模式，列表快速滑动至底部时会被回弹至顶部

### ISSUE THREAD

**Issue by qq1228421450** [YvesCoding/vuescroll#123]
如果滑动的速度过快,回弹的力度会直接将列表回弹至顶部。

**Comment by wangyi7099** [comment]
能否提供一个能够此重现问题的demo？

**Comment by qq1228421450** [comment]
异常效果发到你的邮箱了 wy564654798@126.com

**Comment by wangyi7099** [comment]
重现的代码呢？

**Comment by qq1228421450** [comment]
新建一个了vue项目也出现了这个问题： https://github.com/qq1228421450/vuescrolljs_ex_demo

**Comment by wangyi7099** [comment]
好的 谢谢。   以前出现个 快速往上滑动滚到底部的 现在出现个快速往下滑动滚动到顶部的。 这个bug下个本本修复，

**Comment by qq1228421450** [comment]
(｀・ω・´)   好呐，谢谢作者大大的贡献
