### ISSUE TITLE
vBarVisible hBarVisible not dynamic

### ISSUE THREAD

**Issue by kaiserkiwi** [YvesCoding/vuescroll#124]
Since 4.12.0 we have the classes `vBarVisible` and `hBarVisible` on the `__vuescroll`-Element. Sadly they're not dynamic. If I change the content of the container so it isn't enough to scroll, the classes still are `__vuescroll hasVBar hasHBar vBarVisible hBarVisible`.

Also the horizontal bar isn't even needed (or visible), so there seems to be a general error here.

**Comment by wangyi7099** [comment]
In most cases, parent dom is a fixed size. If your parent dom size or container size changes frequently, you should set sizeStrategy to `number`

**Comment by wangyi7099** [comment]
Hi just tested `4.12.0` . Worked as expected. Could you please provide the code that can reproduce the bug ?

**Comment by kaiserkiwi** [comment]
Ok, I tracked down the problem.

I had the following setting in my global vuescroll config.

```
rail: {
	// other stuff
	keepShow: true,
},
```

If I delete the line everything works as expected. And I think it's the right behavior. Except for the fact, that it still says `hasHBar` and `hasHBarVisible` despite the fact, that I also set the following setting:

```
scrollPanel: {
	scrollingX: false,
}
```

**Comment by wangyi7099** [comment]
Im look into it tonight.

**Comment by wangyi7099** [comment]
4.12.2
