### ISSUE TITLE
鼠标滚动变成缩放

### ISSUE THREAD

**Issue by TheoLin1212** [YvesCoding/vuescroll#126]
![image](https://user-images.githubusercontent.com/16593238/56649550-ecd5e580-66b7-11e9-9345-2d6843e5c880.png)
鼠标滚轮滚动无法生效，反而变成缩放，滚动的时候会改变scale，请问这是什么回事？

**Comment by TheoLin1212** [comment]
是在native模式下，只是想美化滚动条样式

**Comment by wangyi7099** [comment]
这肯定不是native

**Comment by TheoLin1212** [comment]
> 这肯定不是native

确实是设置vuescroll:{mode:'native'}，会被其他影响了吗

**Comment by wangyi7099** [comment]
能否把完整代码贴出来看看  从引入  到配置...

**Comment by TheoLin1212** [comment]
昨晚我想了一下，觉得可能引入了slide，一看果然是...
