### ISSUE TITLE
Vue.use(vuescroll) 提示 <vuescroll> - did you register...

### ISSUE THREAD

**Issue by ruiyong-lee** [YvesCoding/vuescroll#127]
按照文档使用 Vue.use(vuescroll) 提示 `<vuescroll>` - did you register...
只能使用 Vue.component('vuescroll', vuescroll)
这个和vue的版本有关？

**Comment by wangyi7099** [comment]
vue-scroll 中间加个`-`

**Comment by ruiyong-lee** [comment]
好吧，谢谢，眼花了

**Comment by wangyi7099** [comment]
没用过2.0这个版本的。。 好的 我完善一下文档吧。

**Comment by ruiyong-lee** [comment]
@wangyi7099 你可以试下，我这样写没错吧，不生效。
`Vue.use(vuescroll, {
  ops: {
    bar: {
      background: '#5C9ACF',
      onlyShowBarOnScroll: false,
    },
  },
});`
