### ISSUE TITLE
请问怎么给滚动内部的dom添加click事件？

### ISSUE THREAD

**Issue by duoduoing11** [YvesCoding/vuescroll#128]

**Comment by wangyi7099** [comment]
可以通过refs.vs.$el获取到vuescroll 的最外层dom 然后通过 addEventListener 附加事件。

**Comment by duoduoing11** [comment]
> 可以通过refs.vs. $ el获取到vuescroll的最外层dom然后通过addEventListener附加事件。

如果是vuescroll内部的dom呢？直接通过@click或者通过refs获取内部dom addEventListener也无法生效

**Comment by duoduoing11** [comment]
> 可以通过refs.vs.$el获取到vuescroll 的最外层dom 然后通过 addEventListener 附加事件。

而且是在vuescroll slide模式下，所有的事件绑定都无效。。。求解

**Comment by wangyi7099** [comment]
能不能具体到你想获取哪个都没？
