### ISSUE TITLE
请问滚动条压到了内容怎么解决

### ISSUE THREAD

**Issue by wangzhengliang** [YvesCoding/vuescroll#131]
[https://i.loli.net/2019/05/22/5ce50e05c2eba15992.png](url)
如图，滚动条压到了内容。我希望滚动条和轨道一直显示。

**Comment by wangyi7099** [comment]
给内容加个padding啥的即可

**Comment by wangzhengliang** [comment]
给内容加padding没有用，因为内容的宽高远大于滚动区域的宽高，给内容加padding或者margin只能保证滚动条拉到底的时候内容不被滚动条压着。

**Comment by wangyi7099** [comment]
这肯定的 如果没到底部你可以往滚动条对面滑动一点就行了 如果不想滑动的话可以设置滚动条只在滚动的时候显示。
