### ISSUE TITLE
Native scrollbar visible on iPhone XS

### ISSUE THREAD

**Issue by kaiserkiwi** [YvesCoding/vuescroll#134]
I'm in the process of making an old desktop first page responsive. In there we're using vuescroll. The problem is, that the native scrollbar is visible on my iPhone Xs. On my iPad mini it's no problem.

I can recreate the problem on the vuescroll documentation. I would attach a Screenshot of it. But Github seems to have an error on that.

**Comment by wangyi7099** [comment]
What is your  browser of iPhone XS and what is your plugin version？

**Comment by kaiserkiwi** [comment]
Sorry, I forgot to mention that.

Vuescroll Version: 4.12.1
iOS Version: 12.3.1
Browser: Safari

**Comment by wangyi7099** [comment]
https://github.com/YvesCoding/vuescroll/blob/a5b7c1a18eb836d972c326db3b0a708a9dc6e035/src/mode/native/native-panel.js#L51

we add this style  in ios mobile phone: 
```css
-webkit-overflow-scrolling: touch
```

But in some version of ios,  it will cause appearing native scrollbar. So there are two ways to fix it:
1. Adjust the size/position of scrollbar to cover the native scrollbar.
2. Disable this style in global css.
