### ISSUE TITLE
如何获取滚动容器的scrollTop值？

### ISSUE THREAD

**Issue by TheoXiong** [YvesCoding/vuescroll#135]
你好，请问如何获取滚动容器的scrollTop值？

通过浏览器控制台能够查到滚动容器应该是 __panel 元素，能够查到scrollTop值。
通过如下方法也能获取到，但我觉得这个方法不是很友好
```
this.$refs.vuescroll.$el.querySelector('.__panel').scrollTop
```
希望提供一个API直接获取，比如：
```
this.$refs.vuescroll.getScrollTop()
或者 能获取滚动容器元素
this.$refs.vuescroll.getScrollContainer()
```

![image](https://user-images.githubusercontent.com/42533484/59552813-1a575500-8fbe-11e9-9dea-a1b258152fd6.png)

**Comment by wangyi7099** [comment]
https://github.com/YvesCoding/vuescroll/blob/d6e4c5ba44f0fbf71ae0c2c356e9a3ee72192178/src/mode/mix/core.js#L226

直接调取这个api应该能满足你的需求

**Comment by TheoXiong** [comment]
谢谢，这个api可以满足需求。
