### ISSUE TITLE
When using antV G2, the vueScroll plug-in is exceptionally jammed when scrolling

### ISSUE THREAD

**Issue by yinxiaorong** [YvesCoding/vuescroll#137]
When using antV G2, the vueScroll plug-in is exceptionally jammed when scrolling

**Comment by wangyi7099** [comment]
你好，直接用中文交流吧 ， 能否提供一个能重现这个bug的demo？

**Comment by yinxiaorong** [comment]
可能是我的容器内数据体量比较大，我使用了滚动完成的钩子函数handleComplete，在这个函数里面去实例化图表的，感觉是G2实例化太慢了，导致感觉卡顿了

**Comment by wangyi7099** [comment]
跟数据体量确实有关系

**Comment by yinxiaorong** [comment]
有没有好的建议优化?大佬，现在处理就是进入页面的时候，显示在页面的图表开始实例化，但是未在可视区域的图表未初始化，只有等到滚动的时候才去做初始化

**Comment by wangyi7099** [comment]
额。 这个就需要一个例子  我回去研究一下再给你答复吧。

**Comment by yinxiaorong** [comment]
谢谢大佬~

**Comment by yinxiaorong** [comment]
我也研究一下看看能不能行其他方面进行优化

**Comment by wangyi7099** [comment]
能否把你的例子给我？

**Comment by yinxiaorong** [comment]
微信上发你数据了
