### ISSUE TITLE
上拉下拉刷新，能直接用滚动条滚动来加载数据吗

### ISSUE THREAD

**Issue by storagess** [YvesCoding/vuescroll#139]
上拉下拉刷新，能直接用滚动条滚动来加载数据吗 现在的效果是点击的

**Comment by wangyi7099** [comment]
什么意思😳 没懂～

**Comment by wangyi7099** [comment]
监听handlescroll 事件 通过process参数手动调用API触发也可以

**Comment by storagess** [comment]
你的意思是说监听原生的SCROLL 事件。然后调用你提供的 API刷新功能就可以了是吧

**Comment by wangyi7099** [comment]
内置的事件  你搜下文档
