### ISSUE TITLE
微信

### ISSUE THREAD

**Issue by SunshineAfterRain** [YvesCoding/vuescroll#140]

**Comment by wangyi7099** [comment]
什么机型  插件版本？

**Comment by SunshineAfterRain** [comment]
iponeX 微信浏览器跟qq浏览器 滑动不了。自带的浏览器正常

**Comment by wangyi7099** [comment]
安卓是正常的  iOS有很多人反馈了 我也没办法测呀

**Comment by wangyi7099** [comment]
加个样式试试  给  __panel    -webkit-overflow-scrolling: touch

**Comment by wangyi7099** [comment]
close due to no more active.
