### ISSUE TITLE
滚动条BUG

### ISSUE THREAD

**Issue by kouseisama** [YvesCoding/vuescroll#141]
当我不给父级 固定height时   无法出现滚动条   例如：max-height: calc(100% - xxpx) || height: calc(100% - xxpx)

**Comment by wangyi7099** [comment]
设置一下sizeStrategy为number试试

**Comment by kouseisama** [comment]
是设置的number

**Comment by wangyi7099** [comment]
提供一个重新的demo 我查一下

**Comment by kouseisama** [comment]
谷歌上面是好的   火狐上面不行

**Comment by wangyi7099** [comment]
提供一个重新的demo

**Comment by kouseisama** [comment]
等下

**Comment by kouseisama** [comment]
http://118.31.170.46:8000/view_test
老哥你看一下   谷歌好像也有问题。。。

**Comment by wangyi7099** [comment]
好 等下我看看

**Comment by kouseisama** [comment]
好的 谢谢

**Comment by wangyi7099** [comment]
你那个demo不是sizeStrategy 为 number
