### ISSUE TITLE
Cannot read property 'parentNode' of undefined when fast drag scroll to end

### ISSUE THREAD

**Issue by WebKieth** [YvesCoding/vuescroll#143]
I tried to use plugin for infinite scroll.
```javascript
handleScroll(vertical) {
                let position = vertical.scrollTop;
                const maxHeight = parseInt(getComputedStyle(this.$el).maxHeight, 10);
                let getFullHeight = () => {
                    let fullHeight = 0;
                    this.$refs.cartItem.forEach(item => {
                        fullHeight += item.offsetHeight;
                    });
                    return fullHeight
                };
                let fullHeight = getFullHeight();
                if (maxHeight + position > fullHeight * 0.9 && this.pagination.hasNext && !this.loading) {
                    this.waitForLoadMore = true;
                    this.$emit('get-more', () => {
                        fullHeight = getFullHeight();
                        this.waitForLoadMore = false;
                        this.$refs.scroller.refresh();
                    });
                }
            },
```
callback into get-more emitter will execute after pushing new items in array.
If I scroll by mouse it's ok, but when i drag and move bar down too fast, plugin set scroll position to top (without calling scrollTo()) and i get an error:
Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at HTMLDocument.mousemove
1057:
var thubmParent = ctx.$refs.thumb (err undefined) .parentNode;

template:

```
<vue-scroll :ops="scrollOptions" @handle-scroll="handleScroll" ref="scroller">
<div class="c-scroll promo-content__scroll-area cart-list">
                <div slot="scroll-content" name="container"> cutted inner markup </div>
</div>
</vue-scroll>

```

**Comment by wangyi7099** [comment]
I will take a look later. A small tip: you can use  `process` property in arguments.

**Comment by WebKieth** [comment]
@wangyi7099 thanx for a fast review. It was my mistake. I refresh scroll through ref by refresh method after new collection was loaded - this.$refs.scroller.refresh() into getMore emitter arg callback. I remove refresh cb and now plugin works very well)

**Comment by wangyi7099** [comment]
Yes, sometimes using `refresh` too frequently looks a little redundant...
