### ISSUE TITLE
Slide or Native mode

### ISSUE THREAD

**Issue by 11mb** [YvesCoding/vuescroll#144]
Is it possible to dynamicly change the mode of vuescroll? In the documentation example it is possible to have an element toggle between native and slide (https://vuescrolljs.yvescoding.org/guide/configuration.html#mode). 

When I try this, vuescroll does not react on the change in the configuration. Also I tried a refresh on the reference of vuescroll or a `Vuescroll.refreshAll();`

What I basically trying todo is on a mousewheel event, set the mode from slide, to native to have the best of both worlds and let the user scroll with the mousewheel as well.

**Comment by wangyi7099** [comment]
hi！ Can you show your configuration？Let me see if there is something wrong in the config.

**Comment by 11mb** [comment]
Thanks for your reply!

In the computed section of Vue I have this code:
```
computed: {
      ops: function() {
        return {
          vuescroll: {
            mode: this.mode,
            pullRefresh: {
              enable: true,
              auto: true,
              autoLoadDistance: 10,
              tips: {
                deactive: 'Naar vorige blog',
                active: 'Loslaten om door te gaan',
                start: 'Laden...',
                beforeDeactive: 'Successvol geladen!'
              },
            },
            pushLoad: {
              enable: true,
              auto: true,
              autoLoadDistance: 10,
              tips: {
                deactive: 'Naar volgende blog',
                active: 'Loslaten om door te gaan',
                start: 'Laden...',
                beforeDeactive: 'Successvol geladen!'
              },
            }
          },
          bar: { background: '#b9cde5',}
        }
      },
    },
```

In the data properties I have

```
data: function() {
      return {
        mode: 'slide'
      }
    },
```

The event listener for the mousewheel:

```
beforeMount () {
      window.addEventListener('wheel', this.onScroll);
    },
    beforeDestroy () {
      window.removeEventListener('wheel', this.onScroll);
    }
```

The onScroll method:
```
 onScroll() {
        const refresh = (this.mode === 'slide');

        if (refresh) {
          this.mode = 'native';
          this.$refs['scroller'].triggerRefreshOrLoad('load');
        }
      }
```

In the source code of vuescroll I see also a mode 'mixed'. Is it possible to use this mode?

**Comment by 11mb** [comment]
> ou show your configuration？Let me s

Hi! this is still a problem for me.. Is this something you support as you're asking me for the configuration?
