### ISSUE TITLE
How to prevent other click event in slide mode?

### ISSUE THREAD

**Issue by ferrwan** [YvesCoding/vuescroll#145]
Is there a way to prevent other click event when in slide mode?
```Javascript
<vuescroll ops="{ vuescroll: { mode: 'slide' } }">
  <div @click="evn">...</div>
  <div @click="evn">...</div>
  <div @click="evn">...</div>
  <div @click="evn">...</div>
  ...
</vuescroll>
```
I want to prevent the `evn` event when slide using click.

**Comment by wangyi7099** [comment]
I think you need not to prevent `clik event` manually, it seems that `clik event` will not be triggered when you are scrolling by  dragging page.

**Comment by ferrwan** [comment]
Sorry but currently, i'm having this problem. When i'm dragging and if the mouse pointer is in the scroll's and element's (`div`) area, the click event is triggered.
I'm using Vue version `2.6.8` and the vuescroll `4.13.1`

**Comment by wangyi7099** [comment]
Hi I think you can detect cliking event on document or other parent dom of vuescroll by `capture`. And manually use `stopPropagation`.
