### ISSUE TITLE
Vertical scrollbar on the left side

### ISSUE THREAD

**Issue by baldoalessandro** [YvesCoding/vuescroll#146]
Hello, thank you for the project :+1: 
Is there a way to show a vertical scrollbar on the left side of the container?
Does anybody need this feature?
I've implemented this feat here: https://github.com/tomorrowdata/vuescroll/commit/8f22ed57d4560d12c93cbddd1b652256cfcdd4b8
These changes were made on-top of version 4.10.5. If there is interest, and you share the approach, I can rebase everything onto the  `dev` branch,  polish the implementation and open a PR.

**Comment by wangyi7099** [comment]
Thanks for the PR. It seems that it relate to #64  and the feature has been shipped.  [verticalNativeBarPos](https://vuescrolljs.yvescoding.org/guide/configuration.html#verticalnativebarpos)
