### ISSUE TITLE
How using default middle key to X axis?

### ISSUE THREAD

**Issue by 1019588237** [YvesCoding/vuescroll#149]
I want to use vuescroll to the tab Title area. So we use the x-axis. But this may not be implemented from APIs or options.

**Comment by wangyi7099** [comment]
Hi! I'm not queit understanding what you mean.. Can you describe more elaborately?

**Comment by 1019588237** [comment]
> Hi! I'm not queit understanding what you mean.. Can you describe more elaborately?

How to let the mouse middle key default control X axis, not Y axis

**Comment by wangyi7099** [comment]
Currently this is not supported..

**Comment by 1019588237** [comment]
> Currently this is not supported..

Think you

**Comment by 1019588237** [comment]
> Currently this is not supported..

Thank you
