### ISSUE TITLE
作者你好。我有个问题关于溢出隐藏的

### ISSUE THREAD

**Issue by storagess** [YvesCoding/vuescroll#150]
这个插件会在我的元素上套一层会出现溢出隐藏。。这个元素是li. 每个li会加一个伪类。样式是三角形。我这三角形是不能出来的，怎么办。
![image](https://user-images.githubusercontent.com/52128381/61936455-60410900-afbf-11e9-8e57-b5707654059f.png)
我这个需要点击的时候 显示到不同的li.样式

**Comment by wangyi7099** [comment]
正常的滚动条就是这样的吧。。 这个插件是根据正常的滚动条的逻辑做的

**Comment by storagess** [comment]
那这个 溢出了。。我这肯定没办法显示了~

**Comment by wangyi7099** [comment]
通过js动态计算元素的位置 把溢出的部分追加到body上

**Comment by storagess** [comment]
只能变通了

**Comment by storagess** [comment]
谢谢你呀

**Comment by wangyi7099** [comment]
哈哈 不客气
