### ISSUE TITLE
vue-scroll子元素高度设置为100%无效

### ISSUE THREAD

**Issue by songlongfee** [YvesCoding/vuescroll#154]
vue-sroll下的直接子元素高度设置为100%无效

**Comment by songlongfee** [comment]
> <div class="__view" style="position: relative; box-sizing: border-box; min-width: 100%; min-height: 100%; width: -webkit-fit-content;">
这一层只给了min-height:100%;再加个height:100%则正常。

**Comment by wangyi7099** [comment]
css样式覆盖
