### ISSUE TITLE
Horizontal scroll by mousewheel

### ISSUE THREAD

**Issue by snador1977** [YvesCoding/vuescroll#156]
Please add a option for horizontal scrolling by mouse wheel (vertikal mouse wheel). Is there a chance?

**Comment by yalaramesh** [comment]
Hi @wangyi7099 when can i expect this feature?

**Comment by wangyi7099** [comment]
> Hi @wangyi7099 when can i expect this feature?

hi this feature has been shipped which is called wheelDirectionReverse  , you search it in docs of official site.

**Comment by zyphermann** [comment]
on MacOS scrolling with 2 fingers is still broken. If wheelDirectionReverse=false scrilling will always be up/down only, with wheelDirectionReverse=true you can only scroll left/right
