### ISSUE TITLE
我使用demo的自定义滚动条时当我改变duration后无法操作笔记本触摸板进行横向滚动，可以使用鼠标进行横向滚动

### ISSUE THREAD

**Issue by origani** [YvesCoding/vuescroll#158]
demo: https://vuescrolljs.yvescoding.org/zh/demo/

**Comment by origani** [comment]
而且shift+鼠标滚轮的横向移动也失效了

**Comment by wangyi7099** [comment]
我这测得 shift + 滚轮 横向滚动没问题。。。
触摸板有点卡顿。。

**Comment by origani** [comment]
我换了一台笔记本测试，还是不行。
我使用的是chrome浏览器，在没做任何操作之前触摸板横向移动和shift+滚轮 横向滚动是可以的，但当我选择wheel scroll duration后，横向移动就失败了。刷新后又可以了，是不是滚轮监听有问题。。

**Comment by wangyi7099** [comment]
我也是chrome
并且设置了duration

**Comment by origani** [comment]
我的是windows，麻烦你了
