### ISSUE TITLE
Vue3 Supported

### ISSUE THREAD

**Issue by wangyi7099** [YvesCoding/vuescroll#163]
Vuescroll plans to support vue3.

**Comment by 9mm** [comment]
Do you know when you will plan to work on this? Thanks!

**Comment by wangyi7099** [comment]
@9mm In recent time. I will start to work on this.I am thinking about how to implement, refactor, and what feature we will add. So it will be a breaking change release.  It needs a lot of time...  You can also comment what feature you expect!

**Comment by TatianaFomina** [comment]
@wangyi7099 Hi, it there any update on Vue 3 support?

**Comment by miskying** [comment]
毅哥 开整没

**Comment by rbayley** [comment]
Is it compatible with vue3 or we must wait for update?

**Comment by doutatsu** [comment]
Any updates?

**Comment by xxSkyy** [comment]
Bump

**Comment by Winston-Guess** [comment]
Bump 2022?

**Comment by wangyi7099** [comment]
Hi The core code is finished. Im refactorying code with pnpm , monorepo and typescript . So we  need some time to do this...

**Comment by fanlun007** [comment]
any update? thanks

**Comment by wangyi7099** [comment]
Please wait for a few times! I'm refacforing repo woth monorepo and now I have finished the code and writting test files for the code. Writting the open source is not my full-time work but my interest. I have to do some other thing at most of my time! Thanks!
