### ISSUE TITLE
纯文本的容器无效

### ISSUE THREAD

**Issue by guikuan** [YvesCoding/vuescroll#164]
使用时如果div里面是多行文本，插件用起来有些问题，谷歌上面不显示效果，还是原生的滚动条，ie11上面则是一块白色的遮罩层

**Comment by wangyi7099** [comment]
能不能来个重现的demo

**Comment by guikuan** [comment]
抱歉，隔了那么久才回复你，我重现了几次下发现是没问题的但是偏偏项目上的那个地方就有些问问题，也许是别的页面因素干扰到了，总之还是很感谢你的插件，我回去继续研究下原因
