### ISSUE TITLE
Nested onclick events inside vuescroll component

### ISSUE THREAD

**Issue by phen0menon** [YvesCoding/vuescroll#166]
I have horizontal dragscrollable layout that contains some elements with onclick events. However, when scrolling this layout, all events of nested elements trigger too.

I have found a workaround for this, but it doesn't work correct in some cases. For example, when user scrolls extremely fast in some direction (left or right), it triggers bouncing of the layout, so after that the user have to wait some time until bouncing stops, and only after all this stuff elements are becoming available for clicking on them. ([Here's a gif ](https://media.giphy.com/media/Y1XZJd0OqvFjgtmx7y/giphy.gif) that demonstrates how it happens)

If bouncing is disabled, everything work good, but is there a way to make it more accurately?

Here's codesandbox to see clearly what's happening: https://codesandbox.io/s/codesandbox-nuxt-0psc4

Package version: `"vuescroll": "^4.14.4"`
Browser: `Chrome 78.0.3904.70`

**Comment by wangyi7099** [comment]
Hi ! My network to codesandbox is too slow, caould you put the code in other place like codepen?

**Comment by phen0menon** [comment]
Codepen doesn't support npm, so it's hard to connect npm packages with static files without any access to filesystem. Try watching codesandbox, please.

**Comment by wangyi7099** [comment]
you can create a minimalistic reproduction and put it on github. I will clone it to the local.

**Comment by phen0menon** [comment]
@wangyi7099, check it out!

https://github.com/phen0menon/vue-dragscroll-drag-issue

**Comment by wangyi7099** [comment]
> @wangyi7099, check it out!
> 
> https://github.com/phen0menon/vue-dragscroll-drag-issue

Thanks I will check it tomorrow·

**Comment by wangyi7099** [comment]
> I have found a workaround for this, but it doesn't work correct in some cases. For example, when user scrolls extremely fast in some direction (left or right), it triggers bouncing of the layout, so after that the user have to wait some time until bouncing stops, and only after all this stuff elements are becoming available for clicking on them. (Here's a gif that demonstrates how it happens)

Looks like this is not relatived to vuescroll. It's the issue of javascript - `mouseup event` will not trigger on the moving element.

You can add event listener on document and do something when eevent fire. Like so:
```js
{
  mounted() {
    document.addEventListener('mousedown', () => {
      // do something ....
    });
  },
}
```

**Comment by phen0menon** [comment]
> > I have found a workaround for this, but it doesn't work correct in some cases. For example, when user scrolls extremely fast in some direction (left or right), it triggers bouncing of the layout, so after that the user have to wait some time until bouncing stops, and only after all this stuff elements are becoming available for clicking on them. (Here's a gif that demonstrates how it happens)
> 
> Looks like this is not relatived to vuescroll. It's the issue of javascript - `mouseup event` will not trigger on the moving element.
> 
> You can add event listener on document and do something when eevent fire. Like so:
> 
> ```js
> {
>   mounted() {
>     document.addEventListener('mousedown', () => {
>       // do something ....
>     });
>   },
> }
> ```

Is there any other way of solving this problem? I don't want to override `mousedown` event on `document` object.

**Comment by wangyi7099** [comment]
addeventlistener will not override.        
It only adds extra mousedown event handle on document object.
