### ISSUE TITLE
I cannot hide default browser scrollbar

### ISSUE THREAD

**Issue by Teo0303** [YvesCoding/vuescroll#167]
![image](https://user-images.githubusercontent.com/39439363/68041241-f76dd900-fcf1-11e9-8f6f-c927ee5aa8c9.png)

Here's my main.js file
![image](https://user-images.githubusercontent.com/39439363/68041270-094f7c00-fcf2-11e9-8445-567bb7985105.png)

Here's my ProductList component template

![image](https://user-images.githubusercontent.com/39439363/68041368-38fe8400-fcf2-11e9-9cb9-f93b0cb3e720.png)

Css styles for ProducList component

![image](https://user-images.githubusercontent.com/39439363/68041387-474ca000-fcf2-11e9-971d-d735a25db791.png)

Here's my script 

```
<script>
import vuescroll from "vuescroll";
export default {
  components: {
    vuescroll
  },

  data() {
    return {
      ops: {
        vuescroll: {
          mode: "native",
          sizeStrategy: "percent",
          detectResize: true
        },
        scrollPanel: {
          initialScrollY: false,
          initialScrollX: false,
          scrollingX: true,
          scrollingY: false,
          speed: 300,
          easing: undefined,
          verticalNativeBarPos: "left"
        },
        rail: {
          background: "#01a99a",
          opacity: 0,
          size: "6px",
          specifyBorderRadius: false,
          gutterOfEnds: null,
          gutterOfSide: "2px",
          keepShow: false
        },
        bar: {
          showDelay: 500,
          onlyShowBarOnScroll: true,
          keepShow: true,
          opacity: 1,
          hoverStyle: false,
          specifyBorderRadius: false,
          minSize: 0,
          size: "6px",
          disable: false
        }
      }
    };
  }
};
</script>
```

**Comment by wangyi7099** [comment]
Your `.products` div which is the parent of vuescroll should have a fixed height/width value.

**Comment by tilonorrinco** [comment]
Hello!
I have same error. Native scrollbar becomes hidden only if both width and height are set.
Here is an example of what I'm saying:
https://jsbin.com/kijemipoci/

**Comment by wangyi7099** [comment]
> Hello!
> I have same error. Native scrollbar becomes hidden only if both width and height are set.
> Here is an example of what I'm saying:
> https://jsbin.com/kijemipoci/

Normally parent should own a fixed width/height value.  If your parent's values are not fixed, you should try to set `sizeStrategy` to `number`, like so:
```js
ops: {
      vuescroll: {
        sizeStrategy:"number"
      }
    }
```
