### ISSUE TITLE
发现一个问题，Vuescroll设置了滚动条到滑动到最后页面跟随滑动。

### ISSUE THREAD

**Issue by weiqishang** [YvesCoding/vuescroll#172]
我再一个弹出框内部设置了一个滚动条，当混动条滑倒最下面的话应该是不能话动，当移除容器才可以话动，现在就是话动到底部，页面总体的滚动条开始话动了，导致体验不好

**Comment by wangyi7099** [comment]
这是正常的，跟原生的滚动条表现形式一样。
