### ISSUE TITLE
Set z-index for scrollbar elements

### ISSUE THREAD

**Issue by tilonorrinco** [YvesCoding/vuescroll#173]
Hello!
I have a custom scrollbar. Inside of container with scrollbar there is sticky header with high z-index. Because of this z-index custom scroll is under sticky element, but it should be above all elements. My proposal is make z-index for scrollbar elements very high and/or add properties to set its value for handling such situations. 
Sure I can set z-index with css and !important, but this way should be much more cleaner.

**Comment by wangyi7099** [comment]
I don't know what you want to ask? Can you elaborate?

**Comment by tilonorrinco** [comment]
Hi! Sure I can. Here is an example. 
https://jsbin.com/gisomih
Inside scroll container there is red sticky header. It has high z-index (1000). Scroll rail z-index is 1, that's why it pass under sticky header making it look ugly. 
Here is what i want to get:
![image](https://user-images.githubusercontent.com/25035421/69396957-f256e500-0d05-11ea-9a2c-5405f7a6db0e.png)
To handle such situations I need to have posibility to set z-index for rail element. Now I can do it using css (my solution is commented in css section of code), but it would be nice if I could do it in a more cleaner way setting z-index via rail ops.

**Comment by wangyi7099** [comment]
Current, overriding the default css is the only way. I will publish a feature that we can config the style of rail or something else elements at next release.
