### ISSUE TITLE
能否适配一下父容器高度为 max-height 的情况

### ISSUE THREAD

**Issue by lychee-ui** [YvesCoding/vuescroll#176]
```html
<div style="max-height:300px;">
    <vue-scroll>···</vue-scroll>
</div>
```

很多时候我们需要一个块在 max-height 范围内自动伸缩，超过 max-height 范围则显示滚动条。

**Comment by wangyi7099** [comment]
这种情况跟 `height` 没区别把。

**Comment by wangyi7099** [comment]
设置 `sizeStrategy`为 `number` 应该可以。

**Comment by wangyi7099** [comment]
准备加个`maxHeight/maxWidth`选项。 超过此高度出现滚动条。

**Comment by lychee-ui** [comment]
不好意思，我可能没说明白。
![20191218142408.png](https://i.loli.net/2019/12/18/Nwi39qGHTASFBdP.png)

看上面的图，max-height:240px，当内容高度不超过 max-height 的时候，自动适应内容高度。当内容高度超过 240px 时，显示滚动条。

**Comment by wangyi7099** [comment]
好的 我懂了。 这个准备改进

**Comment by lychee-ui** [comment]
👍，多谢了
