### ISSUE TITLE
On a  handle-scroll event preventDefault() doesn't stop the scroll from happening.

### ISSUE THREAD

**Issue by LOUKOUKOU** [YvesCoding/vuescroll#177]
I want to scroll purely programmatically in an upcoming project, therefore disabling any manual scrolling but I can't seem to stop the vuescroll event from scrolling. The values don't seem to want to change e.g.

![image](https://user-images.githubusercontent.com/14559737/71556764-16b08a80-2a45-11ea-877b-bdecb468bea5.png)

**Comment by wangyi7099** [comment]
Hi ! You can try to set`scrollingX` and `scrollingY` to `false` when you dont want it to be scrolled. And set `true` to be scrolled.

**Comment by LOUKOUKOU** [comment]
Fantastic, thanks a lot.

**Comment by LOUKOUKOU** [comment]
Also is there a way to cancel animations?

**Comment by wangyi7099** [comment]
No, but this has been a plan in the feature version.

**Comment by wangyi7099** [comment]
dup of 175
