### ISSUE TITLE
handle-scroll事件可以区别是mousemove触发还是scrollTo触发

### ISSUE THREAD

**Issue by 498755303** [YvesCoding/vuescroll#180]
目前有一需求 需要使用滚动条与其他组件联动滚动  当其他组件滚动时 使用scrollTo控制位置,但同时会触发滚动事件 再次联动另一组件  希望可以在handle-scroll事件上区分是否是 mouse触发还是方法触发的

**Comment by wangyi7099** [comment]
你可以使用scrollto时加个状态自己判断

**Comment by 498755303** [comment]
scrollTo是一定要做的 相当于是两个滚动条 做联动 a 在scroll的时候需要联动b，但是这时会触发b的scroll事件 ,该事件又会联动a做scrollTo，导致a的scroll事件触发

**Comment by wangyi7099** [comment]
可以判断出来是谁触发的

**Comment by 498755303** [comment]
怎么判断呢？

**Comment by wangyi7099** [comment]
比如你左边是vuescroll， 右面的联动的。
右面滚动的时候加个状态 标志者是右面触发 然后再handleSCROLL里加个判断，如果是右面触发的就不需要调用了。

**Comment by 498755303** [comment]
也就是说  怎样让scrollTo这个方法不会触发scroll事件

**Comment by 498755303** [comment]
看起来 可能您误解了我的意思    就好像 我们在使用markdown的时候 编辑和预览两侧联动一样 在左侧的scroll事件上 调用右侧的scrollTo方法  右侧一样 这样就会导致左右两侧会循环触发scroll事件的触发

**Comment by 498755303** [comment]
左侧的scroll事件:this.$refs.rightScroll.scrollTo(x,y),
