### ISSUE TITLE
scrollingY set to true but its not working

### ISSUE THREAD

**Issue by AmrBinBashir** [YvesCoding/vuescroll#184]
here is my code 
```
<template>
	<vue-scroll :ops="ops" ref="vs" id="vue-scroll">
		<div 
                        id="results-container"
			v-for="(result, index) in dictResults"
			:key="index">
			<result-item :resultItem="result"/>
		</div>
	</vue-scroll>
</template>
<script>
export default {
	data() {
		return {
		       dictResults:['dummy','dummy','dummy','dummy','dummy','dummy',],
			ops: {
				scrollPanel: {
					scrollingX: false,
					scrollingY: true,
					speed: 300
				},
				bar: {
					background: "rgba(197, 20, 20, 0.7)",
					keepShow: true
				}
			}
		};
	}
</script>
<style scoped>

#vue-scroll {
	max-height: 360px;
}
</style>
```
so you see i have scrollingY set to ture but there is no scrolling happening and no scrollbar and when i set scrolling X to true, horizontal scorlling works but not vertical and i want vertical only. 

when i toggle the scollingX in vue tools i can see a <bar> component added to <scrollPanel> but when i try the same with scrollingY nothing happens.

**Comment by wangyi7099** [comment]
max-height doesn't be supported before the version of `4.14.4 ` . Use `height` instead
