### ISSUE TITLE
Doesn't scroll automatically to focused input

### ISSUE THREAD

**Issue by ngstwr** [YvesCoding/vuescroll#186]
I have a lengthy form having lots of input elements, everything works fine except when I use tab to focus to next input. Input element get focused but some of the inputs are not visible on current scroll position. 

When not using vuescroll it works fine. It scrolls to the focused element if the element was out of view at the time of focus.

Any solution?

**Comment by wangyi7099** [comment]
please provide a minimalist reproduction.

**Comment by ngstwr** [comment]
Sorry about that! It's working now, it might have been mistake on my end.
