### ISSUE TITLE
It does not work when parent node(div) not set a fixed width

### ISSUE THREAD

**Issue by wossig** [YvesCoding/vuescroll#188]
Hi guy,  i'm very happy to use vuescroll, but seems there have an issue,  when parent node didn't have a fixed height, the vuescroll won't work. Is this an issue or have other config to avoid this?
following  are some snippet for my issue:

no  fixed height:
``` html
<div class="list" style="/* height: 312px; */">
    <div class="__vuescroll"
        style="height: 100%;width: 100%;padding: 0px;position: relative;overflow: hidden;/* overflow-y: hidden; */">
        <div class="__panel" style="position: relative; box-sizing: border-box; height: 100%; overflow: hidden;">
            <div class="__view"
                style="position: relative; box-sizing: border-box; min-width: 100%; min-height: 100%; width: -webkit-fit-content;">
                <ul class="d-flex flex-wrap">
                    <li role="button">生物领域 (10039)</li>
                    <li>...</li>
                </ul>
                <div
                    style="display: block; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; border: none; padding: 0px; margin: 0px; opacity: 0; z-index: -1000; pointer-events: none;">
                    <object type="text/html" tabindex="-1" data="about:blank"
                        style="display: block; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; border: none; padding: 0px; margin: 0px; opacity: 0; z-index: -1000; pointer-events: none;"></object>
                </div>
            </div>
        </div>
    </div>
</div>
```
screenshot:
![image](https://user-images.githubusercontent.com/22833218/75870737-61d08a80-5e46-11ea-9218-3af09f172e60.png)

fixed height, it works:
![image](https://user-images.githubusercontent.com/22833218/75870876-98a6a080-5e46-11ea-8cad-c9a8a6c8e5ce.png)

**Comment by wossig** [comment]
i resolved this by myself, my solution is wrap a another div(call "div1") above <vue-scroll>, and set the parent div( div1 ) and inner div(wrapped by vue-scroll) same css(max-heigth:xxx), it works now,  here's snippet:
`<div class="list-container">
                        <vue-scroll :ops="scroll_ops" v-cloak>
                            <div class="list">
                                <ul class="d-flex flex-wrap">
                                    <li role="button">生物领域 (10039)</li>
                                   <li>........</li>
                                </ul>
                            </div>
                        </vue-scroll>
                    </div>`

and css:
`.list-container {
                 ...
                max-height: 19.5rem;
                .list {
                    max-height: 19.5rem;
                }
            }`



finally, it works for me,  but i still wander that is there a  another elegant way to achieve the goal?

**Comment by wangyi7099** [comment]
Try [`maxHeight`](https://vuescrolljs.yvescoding.org/zh/guide/configuration.html#maxheight).

**Comment by wossig** [comment]
> Try [`maxHeight`](https://vuescrolljs.yvescoding.org/zh/guide/configuration.html#maxheight).

Yeah, thank for reply, maybe `maxHeight`  should be a solution, but not good since that in most time we need responsive layout for our website, and if we use `maxHeight`,  we can not share same config for multiple instances.

And  seems the the package in [https://unpkg.com/vuescroll](url) already be updated, i saw that the scroll wrapper div already moved to up of target(the div we want implement scroll bar), so this issue resolved.

update the screenshot which can see that the wrapper div changed
 
![image](https://user-images.githubusercontent.com/22833218/75884235-69505d80-5e5f-11ea-95dd-2025e8d66427.png)

YOU ARE SO FAST!!!
![image](https://user-images.githubusercontent.com/22833218/75884456-d06e1200-5e5f-11ea-8ee9-d278dd8dcfbe.png)
