### ISSUE TITLE
Chrome 最新版 上  垂直滚动条无法 滚动到100%。导致无法触发父级的滚动。

### ISSUE THREAD

**Issue by yuncode** [YvesCoding/vuescroll#190]
process: 0.9988024134835797,

**Comment by wangyi7099** [comment]
需要一个重现的demo

**Comment by yuncode** [comment]
> 需要一个重现的demo
@wangyi7099  谢谢你的库。 demo 如下 win10 系统 
https://codepen.io/oceanstick/pen/wvajOqW

**Comment by yuncode** [comment]
demo 已更新

**Comment by wangyi7099** [comment]
我这能滚到1  没问题的 建议你多找几个人的电脑试试

**Comment by yuncode** [comment]
家里没有多余电脑。 出现在我的笔记本Chrome上 ，而且 div是某些特定的高度值的情况，并不是所有情况。
希望这个issue 先留着，说不定别人也会遇见类似情况。

**Comment by yuncode** [comment]
我特意做了个原生js 小实验。证明是 chrome 的bug，https://codepen.io/oceanstick/pen/VwLEzjq
