### ISSUE TITLE
Basic Example

### ISSUE THREAD

**Issue by adrianwix** [YvesCoding/vuescroll#192]
Is it possible to add a simple example to get it working?

**Comment by mike-battistella** [comment]
I would also like to see a very simple example for using it directly in a HTML environment, not in a .vue component. Also I'm using it in a browser environment without webpack. The <vue-scroll> component is not interpreted/re-rendered, it appears as <vue-scroll> node in the HTML.

**Comment by wangyi7099** [comment]
Here is the [Basic Example](https://github.com/YvesCoding/vuescroll/blob/dev/examples/base-scroll.html)

**Comment by mike-battistella** [comment]
Thanks. I have tried it, but the component tag is not processed. All other VUE directives are processed and replaced in the HTML code. But the vue-scroll tag remains. 

Here is the HTML directly from the Firefox inspector:




```
<body>
    <vue-scroll :ops="ops">

        <div id="page-01" class="page"><div id="logo"><img src="images/porsche-wortmarke.svg" alt="Porsche"></div> <div class="section-welcome"><div class="text-welcome">Willkommen im</div> <div class="text-center-name">Porsche Zentrum Zug</div></div> <div class="section-start"><div class="section-image"><img src=""></div> <div class="section-button"><button class="theme-red">Button 1</button></div></div><div class="section-start"><div class="section-image"><img src=""></div> <div class="section-button"><button class="theme-red">Button 2</button></div></div><div class="section-start"><div class="section-image"><img src=""></div> <div class="section-button"><button class="theme-red">Button 3</button></div></div><div class="section-start"><div class="section-image"><img src=""></div> <div class="section-button"><button class="theme-red">Button 4</button></div></div></div>
        <!-- end: Page 01-->
    </vue-scroll>


    <!-- JavaScript at end of body for optimized loading -->
    <!-- Grassfish libraries -->
    <script src="/gv2/gf/GFWebHtml/lib/gfWizardBase/src/gfWizardBase.js"></script>
    <script src="js/materialize.min.js"></script>
    <script src="js/vue.js"></script>
    <script src="js/vuescroll.min.js"></script>

    <script type="text/javascript" src="js/vuescroll-native.min.js"></script>
    <script src="js/main.js"></script>

</body>

```

**Comment by mike-battistella** [comment]
Could it be that the script tag for vuescroll has to be in the head section of the HTML file? If I move it from the end of the <body> tag to the <head> section the <vue-scroll> tag  is processed and replaced with a <div class="__vuescroll mouseEnter"> tag.
