### ISSUE TITLE
Denying load of chrome-extension

### ISSUE THREAD

**Issue by adrianwix** [YvesCoding/vuescroll#193]
I am getting a 
`Denying load of chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.`
`GET chrome-extension://invalid/ net::ERR_FAILED`
When using this package.
Any idea what may be happening?

**Comment by adrianwix** [comment]
Deleting Mega eliminates the error. But why is a package trying to load mega?

**Comment by wangyi7099** [comment]
When trying to detect resize, vuescroll will append a `Object` element to your container. It may cause this error.      You can set `{detectResize: false}` to see whether the error will still show or not.
