### ISSUE TITLE
handle-scroll 以后不执行handle-scroll-complete 

### ISSUE THREAD

**Issue by crisbb** [YvesCoding/vuescroll#194]
handle-scroll 以后不执行handle-scroll-complete ？是我代码问题吗
 @load-start="handleLoadStart"
    @handle-scroll-complete="handleComplete"
 handleComplete () {
      console.log(1)
      this.$emit('scroll-finish')
    },
    handleScroll () {
      console.log(2)
      this.$emit('scrolling')
    },
    @scroll-finish="canClick = true"
          @scrolling="canClick = false"
因为列表需要点击事件，所以滚动时候不能点击 但是滚动结束监听不生效 有时候

**Comment by wangyi7099** [comment]
请提供一下重现的demo

**Comment by crisbb** [comment]
代码有点多 就是我想监听列表滚动时候不能触发点击事件，滚动监听结束才可以触发里面的每一项点击事件

**Comment by crisbb** [comment]
但是发现现在滚动结束监听有时候不触发。不知道怎么解决。

**Comment by crisbb** [comment]
列表里面有点击事件

**Comment by crisbb** [comment]
能不能加微信讨论一下哈 cristibaby

**Comment by vasttian** [comment]
> 请提供一下重现的demo

官网的 Demo，`handle-scroll-complete` 事件也是不触发的
[https://vuescrolljs.yvescoding.org/zh/guide/event.html#handle-scroll-complete](https://vuescrolljs.yvescoding.org/zh/guide/event.html#handle-scroll-complete)

**Comment by wangyi7099** [comment]
> 官网的 Demo，`handle-scroll-complete` 事件也是不触发的

只有点击轨道 或者 调用 api完成的一次滚动过程才能判断出scroll-complte时间。 用鼠标滚轮的判断不出来的，除非你设置了`wheelScrollDuration`

**Comment by vasttian** [comment]
> > 官网的 Demo，`handle-scroll-complete` 事件也是不触发的
> 
> 只有点击轨道 或者 调用 api完成的一次滚动过程才能判断出scroll-complte时间。 用鼠标滚轮的判断不出来的，除非你设置了`wheelScrollDuration`

Thx!
