### ISSUE TITLE
官网文档错误，望修改

### ISSUE THREAD

**Issue by BrotherMa** [YvesCoding/vuescroll#198]
https://vuescrolljs.yvescoding.org/zh/guide/api.html#getscrollprocess

“用法”中，第二块
`const { scrollTop, scrollLeft } = this.$refs["vs"].getPosition();
console.loo(scrollTop, scrollLeft);`
第二行console.log错写成console.loo了

**Comment by wangyi7099** [comment]
晚上回去就改。
