### ISSUE TITLE
Scrollbar cuts off Elements

### ISSUE THREAD

**Issue by amrap030** [YvesCoding/vuescroll#203]
Hello, I have an issue with the Scrollbar. As soon as I implement the vuescroll Element it cuts off some pixels of my Elements. On the first picture you can see how the original looks and the second picture is with the vuescroll element as a wrapper around the element. You can see that a little bit of the shadow is cut off on the sides and at the bottom element the dashed border too. How can this be fixed?

<img width="396" alt="Bildschirmfoto 2020-05-25 um 12 52 52" src="https://user-images.githubusercontent.com/35061229/82806854-f1566a00-9e86-11ea-9379-074870249d64.png">

<img width="402" alt="Bildschirmfoto 2020-05-25 um 12 51 57" src="https://user-images.githubusercontent.com/35061229/82806872-f87d7800-9e86-11ea-9321-1879f94b9bc3.png">

**Comment by wangyi7099** [comment]
add a wrapper to your elements and set padding.

**Comment by amrap030** [comment]
Ok thank you I fixed it, but I noticed that scrolling only works in Chrome and Firefox but not in Safari. It doesn't work in Safari on my MacBook and Ipad.
