### ISSUE TITLE
这算是bug吗???

### ISSUE THREAD

**Issue by ghost** [YvesCoding/vuescroll#205]
[演示网址](https://codesandbox.io/s/mystifying-lumiere-7zpwv?file=/src/components/HelloWorld.vue:289-290)

很奇怪  只要内部有h1 或者带有margin的属性 就会出现滚动条!
而且内容只有一行 父元素也是有高度的!!

尝试了好多参数 也不行 后来以为是 css `calc`的原因 给定高 也行不通!!! 难道里面就不能有一点点padding 或者margin吗?

### 代码:
```
<template>
  <div class="app-main">
    <vue-scroll>
      <h1>111</h1>
    </vue-scroll>
  </div>
</template>

<script>
import VueScroll from "vuescroll";
export default {
  name: "HelloWorld",
  components: { VueScroll }
};
</script>


<style scoped >
.app-main {
  height: calc(100vh - 90px);
}
</style>
```

**Comment by wangyi7099** [comment]
margin也算高度的
