### ISSUE TITLE
Is it posible affect to textarea?

### ISSUE THREAD

**Issue by donggyu04** [YvesCoding/vuescroll#206]
```
<vue-scroll>
    <textarea v-model="test.description"></textarea>
</vue-scroll>
```

Is it possible affect to textarea?
It has own scroll in `overflow:visible(default)` so, not effect to created wrapping div from vue-scroll.

thanks in advance.

**Comment by wangyi7099** [comment]
no
but you can try to make textarea [auto height](https://stackoverflow.com/questions/454202/creating-a-textarea-with-auto-resize)

**Comment by donggyu04** [comment]
@wangyi7099 

Thanks
