### ISSUE TITLE
maxHeight bug?

### ISSUE THREAD

**Issue by mwleinad** [YvesCoding/vuescroll#207]
So, if I set a maxHeight, but my content height is less than maxHeight I get a weird flickering of classes
https://app.vidgrid.com/view/Xh4ByWTBV8ar < Here's a video so you know what I'm talking about

I just modified the height of the content element in your example and I can reproduce it.
Is there any setting to prevent that flicker?

Thanks!

**Comment by wangyi7099** [comment]
Thanks, it is really a bug. I will fix it in next minor release.
