### ISSUE TITLE
横向滚动无法滑动

### ISSUE THREAD

**Issue by smalltimoo** [YvesCoding/vuescroll#209]
被vuescroll包裹的内部元素中有一个可以横向滚动的容器，但是在vuescroll包裹下无法滚动

**Comment by wangyi7099** [comment]
请提供一下能重现此bug的demo

**Comment by smalltimoo** [comment]
###我制作了连个小视频来描述这个问题，你可以看一下，两者唯一的区别就是vuescroll标签的包裹
[waitfix.zip](https://github.com/YvesCoding/vuescroll/files/4941371/waitfix.zip)

**Comment by wangyi7099** [comment]
这是故意这么设计的，vuescroll slide模式默认会拦截鼠标点击事件。
尝试变更一下
`preventDefault `或者`preventDefaultOnMove `试下。 用法在官网能搜到的

**Comment by smalltimoo** [comment]
我尝试查询了下这两个关键字，结果并没有任何反馈，组件内部是有替代原生横向滑动的逻辑吗

**Comment by wangyi7099** [comment]
怎么替换的? 请出示一下代码

**Comment by smalltimoo** [comment]
我没有替换，我是在想你们是不是在组件内部实现了替换原生滑动的逻辑

**Comment by smalltimoo** [comment]
我在[官网](https://vuescrolljs.yvescoding.org/zh/)查询了关键字**preventDefault**和**preventDefaultOnMove**，没有得到任何反馈

**Comment by wangyi7099** [comment]
1.确实替换了原生的滑动。
2.在slide模式配置页面 按ctrl+f 查找就能找到了
http://127.0.0.1:3000/zh/guide/configuration.html#vuescroll-slide-%E6%A8%A1%E5%BC%8F

**Comment by smalltimoo** [comment]
谢谢，这个是可以的，不过我觉得这个配置项不应该默认为true，里面子项横向滑动应该是很常见的需求尤其是移动端

**Comment by wangyi7099** [comment]
好的，这个问题我会慎重考虑的。要改也是在一个大的版本里改这个。否则会导致其他使用这个特性的人遇到问题。
