### ISSUE TITLE
当页面缩放后，刷新，再回到100%尺寸，样式会出问题

### ISSUE THREAD

**Issue by kooriookami** [YvesCoding/vuescroll#211]
![image](https://user-images.githubusercontent.com/38392315/88121922-c0ca4c80-cbf9-11ea-84bb-9fffcbac03d7.png)
上图是页面放大500%后刷新，恢复100%的样子，同时出现了两种滚动条

**Comment by wangyi7099** [comment]
自己监听一下缩放的事件再调用一下refresh试试

**Comment by kooriookami** [comment]
试了是无效的，只有刷新才起作用。原生的滚动条是没有这个问题的。还有个问题就是页面缩放时，滚动条的宽度会有问题，导致滚动条内部元素偏移

**Comment by wangyi7099** [comment]
这不属于bug吧，实际场景不会有人这么玩的
