### ISSUE TITLE
How do I enable and disable scrolling when a vuescroll component is fully mounted?

### ISSUE THREAD

**Issue by 6ondarenko** [YvesCoding/vuescroll#213]
Case: how disable scrolling when pop-up opened and enable scrolling when pop-up closed?

**Comment by wangyi7099** [comment]
hi! @6ondarenko May I know why you want do this?

**Comment by 6ondarenko** [comment]
Hi, @wangyi7099! I want do this because when login pop-up opened I want disable global scrolling and continue global scrolling when login pop-up (modal window) to be closed. My solution is currently:
```
<vuescroll
    ref="vuescroll"
    :ops="globalScrollbarOps"
    :key="componentKey"
>
    ...
</vuescroll>

<script>
import { mapGetters } from 'vuex'

export default {
  name: 'CustomVerticalScroll',
  data () {
    return {
      componentKey: 0
    }
  },
  computed: {
    ...mapGetters(['globalScrollbar', 'globalScrollbarOps '])
  },
  methods: {
    forceRerender () {
      setTimeout(() => {
        this.componentKey++
    }
  },
  watch: {
    // true | false
    globalScrollbar () {
      this.forceRerender()
    }
  }
}
</script>
```

I mutate globalScrollbarOps (ops.scrollPanel.initialScrollY = false, ops.scrollPanel.initialScrollX = false) and globalScrollbar. But if not re-render vuescroll component new options not working. I do this by changing the key: https://michaelnthiessen.com/force-re-render/

**Comment by wangyi7099** [comment]
Hi I think you can try `refresh`. api,

**Comment by 6ondarenko** [comment]
@wangyi7099 `this.$refs.vuescroll.refresh()` not working. New options apply only when re-rendering a vuescroll component((

**Comment by 6ondarenko** [comment]
I solved my ploblem:

```
this.$refs.vuescroll.mergedOptions = this.globalScrollbarOps // updated options
this.$refs.vuescroll.refresh()
```

@wangyi7099 Thanks a lot!)

**Comment by wangyi7099** [comment]
ok! I think issue can be closed!

**Comment by TuringJest** [comment]
Is there no prop to enable/disable scroll behavior? It would be very useful.
