### ISSUE TITLE
Nested scroll not working

### ISSUE THREAD

**Issue by salakhovilia** [YvesCoding/vuescroll#219]
when using nested architecture, scroll does not work, example:
```
<div>
<vue-scroll> // disable scrollY
<div id="scrollX">...</div>
<vue-scroll> // disable scrollX
<div id="scrollY">...</div
</vue-scroll>
</vue-scroll>
</div>
```

**Comment by wangyi7099** [comment]
can you provide a detail example@

**Comment by salakhovilia** [comment]
https://codesandbox.io/s/fervent-feather-btinu?fontsize=14&hidenavigation=1&theme=dark

**Comment by wangyi7099** [comment]
This is excepted. Because inner vuescroll size is the same as its parent's.....  But parent's size height overflow is hidden.So innerHeight is the same as child height ---- 5000px

**Comment by salakhovilia** [comment]
Using nested scrolls is not possible, did I understand correctly?

**Comment by wangyi7099** [comment]
Hi you can specify the concrete height for inner vuescroll
