### ISSUE TITLE
body scroll lock

### ISSUE THREAD

**Issue by fateme572** [YvesCoding/vuescroll#220]
Hi 
How to enable body scroll locking without breaking scrolling of a target element???

**Comment by wangyi7099** [comment]
Can you elaborate ?

**Comment by fateme572** [comment]
Ok!
I want to prevent body from scrolling as long as I scroll on the element containing the v-scroll even when the scroll of the element is finished and I am still scrolling on the element.
The v-scroll now works in such a way that the body scrolls after the scrolling of the element is completed.
Was I able to get what I meant?

**Comment by wangyi7099** [comment]
v-scroll seems not relative to vuescroll ?

**Comment by fateme572** [comment]
There is a typo, I mean the vuescroll

**Comment by wangyi7099** [comment]
hi this behavior is intended. vuescroll will simulate native scroll behavior.
