### ISSUE TITLE
How to trigger scroll

### ISSUE THREAD

**Issue by yalaramesh** [YvesCoding/vuescroll#222]
Hi,

my use case is like i am using two scrollbars in one single page in two sections, if i am scroll the one page i need to be auto scroll the second page also, how i archive this some one help me.

Like below, if i scroll the 'header-section-container' it automatically scroll the 'footer-section-container' also vice versa.
Thanks advance.

`<vue-scroll ref="vuescroll" :ops="vuescrollOptions">
      <div class="header-section-container">.........</div>
</vue-scroll>`

`<vue-scroll ref="vuescroll" :ops="vuescrollOptions">
      <div class="footer-section-container">.........</div>
</vue-scroll>`

**Comment by wangyi7099** [comment]
detect handle scroll event and use scroll API to scroll another scroll
