### ISSUE TITLE
handle-scroll-complete $emit by <VueScroll>

### ISSUE THREAD

**Issue by mahentoo** [YvesCoding/vuescroll#227]
I noticed that the `<Bar>` component emits the **setBarDrag** event and I imagine that this event marks the beginning and end of scrolling through the bar (true and false, respectively).
Would it be possible to issue the **handle-scroll-complete** event when scrolling through the bar is complete?

**Comment by wangyi7099** [comment]
Yes.   But click the bar this hehavior will also trigger setBarDrag and this should not be considered to handle-scroll-complete

**Comment by mahentoo** [comment]
Now I get it.
I changed the approach I was using and it is satisfactory to use only @handle-scroll, like #222.
