### ISSUE TITLE
能否支持滑动轨道和滑动块的样式自定义， 主要是宽、高、位置等的调整

### ISSUE THREAD

**Issue by AnneDong** [YvesCoding/vuescroll#230]
目前的滑动条太长 了，用户体验不是很好。想要做那种短小的滑块。

在浏览器端试着改了下__rail-is-horizontal的width，发现可以的, 但是写在代码中，这个宽度是不生效的，即使加了important都无效。所以是不是不支持自定义样式的？

![image](https://user-images.githubusercontent.com/20206950/99363752-15ec4580-28f0-11eb-8482-17d73efd2645.png)

**Comment by wangyi7099** [comment]
代码中什么样的
