### ISSUE TITLE
native模式下能不能支持鼠标点击按住滚动

### ISSUE THREAD

**Issue by shengxq** [YvesCoding/vuescroll#232]
在电脑上slide模式下 鼠标左键按住就可以滚动  但 滚轮和 触摸屏不好用
native模式下   滚轮和 触摸屏好用,  鼠标左键按住滚动又不好用
能不能 在native模式下  可以标左键按住滚动呢

**Comment by wangyi7099** [comment]
本来就支持鼠标拖动 触摸屏应该也没问题

**Comment by shengxq** [comment]
native模式下 不支持 鼠标拖动啊

**Comment by shengxq** [comment]
再 windows浏览器上  native模式下 不支持 鼠标拖动啊

**Comment by shengxq** [comment]
@mouseup.native="e=>{zzzy=-10000;}" @mousedown.native="e=>{zzztop = $refs.mx.getPosition().scrollTop;zzzy= e.y;}" @mousemove.native="onmousemove"

onmousemove(e) {
            if (window.getSelection().toString().length > 0) return;
            if (this.zzzy > -10000 && Math.abs(this.zzzy - e.y) > 5) {
                window.getSelection().removeAllRanges();
                this.$refs.mx.scrollTo({ y: this.zzztop + this.zzzy - e.y }, 0, 'easeInOutQuad');
            }
        }


增加点代码 很简单 就能实现了
不过能不能加到 控件里啊 
要不 要每个地方 都要加这些代码
