### ISSUE TITLE
handle-scroll事件返回的nativeEvent对象里的scrollTop为0

### ISSUE THREAD

**Issue by lchreal6** [YvesCoding/vuescroll#236]
监听滚动handle-scroll事件里返回的scrollTop一直为0，返回不正确，应该要返回实际的scrollTop值

**Comment by wangyi7099** [comment]
暂时用 API获取scrolltop

**Comment by wangyi7099** [comment]
我试了下 能获取到 你这是slide模式么

**Comment by lchreal6** [comment]
> 我试了下 能获取到 你这是slide模式么

是的，我改的是slide模式

**Comment by wangyi7099** [comment]
> > 我试了下 能获取到 你这是slide模式么
> 
> 是的，我改的是slide模式

好的，我明天发布会发布一版
