### ISSUE TITLE
同一个页面中出现两个或两个以上使用scroll的相同组件时出现的问题

### ISSUE THREAD

**Issue by legloo** [YvesCoding/vuescroll#238]
<img width="1138" alt="1608687751806_EECD856E-1ADD-460D-8AF3-C5CE1E3C79BC" src="https://user-images.githubusercontent.com/23420270/102949439-446acb00-4503-11eb-9874-783252c0c02b.png">

version:vuescroll@4.17.0

```get opts() {
    return {
      vuescroll: {},
      scrollPanel: {},
      rail: {
        // keepShow: true,
      },
      bar: {
        keepShow: true,
        // hoverStyle: false,
        onlyShowBarOnScroll: true, //是否只有滚动的时候才显示滚动条
        background: this.themeColor, //滚动条颜色
        opacity: 1, //滚动条透明度
        size: "4px",
      },
    };
  }```

一样的配置 为什么最后一个生成的组件会出现滚动条呢

**Comment by zhuyuhaoliar** [comment]
详细说明下：两个相同组件，出现在同一个页面，高度、宽度相同，内部元素没有超出范围所以按理来说不应该出现滚动条，但是不管keepShow设置与否，第二个（最新的）那个组件一定会出现滚动条（x轴，y轴没有），但是实际上是无法滚动的。

**Comment by wangyi7099** [comment]
请提供一个重现的demo
