### ISSUE TITLE
横向滚动时出现双滚动条

### ISSUE THREAD

**Issue by jinglun2019** [YvesCoding/vuescroll#242]
横向滚动时出现双滚动条,看起来好像是flex属性把容器给硬撑大了，上周五折腾了一个下午，不知道怎么解决。
https://github.com/jinglun2019/vue-scroll-double-scroll/tree/master/src
Demo放在views/home文件夹下,
测试环境Firefox85.0b7，edge87.0；两个浏览器都出现双滚动条
![图片](https://user-images.githubusercontent.com/57926735/104255513-367de980-54b4-11eb-87a7-cd06de17d8be.png)

**Comment by wangyi7099** [comment]
要么给`.scroll-box `设置一个高度值，要么设置sizeStrategy为number

```js
<vue-scroll
          :ops="{
            vuescroll: {
              sizeStrategy: 'number',
            },
          }"
        >
          <div class="data-box">
            <div
              class="some-data"
              v-for="(item, index) in 99"
              :key="index"
            >
              09876&nbsp;
            </div>
          </div>
        </vue-scroll>
```
