### ISSUE TITLE
给滚动条内部div添加mousedown事件无法触发。

### ISSUE THREAD

**Issue by lxsisKing** [YvesCoding/vuescroll#244]
我通过this.$refs.vs.$el获取到最外层div后，再通过this.$refs.vs.$el.lastChild.firstChild.firstChild获取到滚动块的div。但是对该div通过addEventListener绑定mousedown事件无效。后来我发现即使是直接对最外层div(this.$refs.vs.$el)添加mousedown事件，也无法在滚动块内进行触发。但是其他事件均可以生效（如：mouseup、mousemove、click）。
代码如下：
```
        let scrollDiv = this.$refs.vs.$el.lastChild.firstChild.firstChild
        scrollDiv.addEventListener("mousedown", this.scrollDraingMouseDownEvent)
```

**Comment by wangyi7099** [comment]
请提供一个重现的demo
