### ISSUE TITLE
Refresh on v-for

### ISSUE THREAD

**Issue by aymericingargiola** [YvesCoding/vuescroll#247]
Hello, i like a lot your component but i have an issue with dynamics v-for (calling jsons from store), every time i do `this.$refs.firstRunFloorsScroller[0].refresh()` when i get a new entry in the v-for to update the scroller status it goes back to the begining, is it possible to easily keep the current position ?

Actually i'm getting it working with weird code like this :
`this.$refs.firstRunFloorsScroller[0].scrollTo({x:"100%"}, 1500)
setTimeout(() => {
    this.$refs.firstRunFloorsScroller[0].refresh()
}, 1500);
setTimeout(() => {
    this.$refs.firstRunFloorsScroller[0].scrollTo({x:"100%"}, 1500)
}, 1500);`

**Comment by wangyi7099** [comment]
please provide your code
