### ISSUE TITLE
ScrollyX/Y still shows scroll bar

### ISSUE THREAD

**Issue by EricTalv** [YvesCoding/vuescroll#249]
I wanted to disable the X scrollbar and not to show it.

I used this :

```

        scrollPanel: {
          scrollingY: false,
        },
```

However this only just disables the scrolling in that direction, not hide that scrollbar entirely,
how can I do that?

**Comment by wangyi7099** [comment]
just using css to overflow

**Comment by avpuchkova** [comment]
@EricTalv in my case it works:
`          vuescroll: {
            mode: 'slide',
          },
          scrollPanel: {
            scrollingY: false
          },`
