### ISSUE TITLE
Horizontal Bar position

### ISSUE THREAD

**Issue by avpuchkova** [YvesCoding/vuescroll#251]
Is it possible to set horizontal Bar to the top?

**Comment by wangyi7099** [comment]
override default style by your own css

**Comment by avpuchkova** [comment]
@wangyi7099 Can you show an exapmle please. It is not work:
`<style scoped>
.__rail-is-horizontal{
  position: absolute;
  top: 2px !important;
  bottom: 0 !important;
}
</style>`

**Comment by glowens** [comment]
Any update on this?

**Comment by supremeabraxas** [comment]
@avpuchkova  Its the selector. I got it to work vertically.

[class^="__rail-is-vertical"] {
  position: absolute;
  left: 2px;
}
