### ISSUE TITLE
Need Help!! maxHeight not working

### ISSUE THREAD

**Issue by nasirDoe** [YvesCoding/vuescroll#255]
i use this plugin on nuxt.js, any solution. the base component always `height: 100%`. Thank you

**Comment by wangyi7099** [comment]
please provide the code

**Comment by ckap** [comment]
maxHeight is a property of scrollPanel.  Make sure that you've formatted your ops correctly.  Ex: 

```
<vue-scroll
  :ops="{
    scrollPanel: {
      maxHeight: 10
    }
  }"
>
</vue-scroll>
```

**Comment by nasirDoe** [comment]
I wrote my code like below
`<vue-scroll
  :ops="{
      maxHeight: 10
  }"
>
</vue-scroll>`
because in plugin documentations like this, maybe you miss in documentation. But thanks for your answer, i appreciated it. i'll try soon
![miss-documentation](https://user-images.githubusercontent.com/16643567/121033648-92843a00-c7d6-11eb-8d18-0fb97327bfa8.png)
