### ISSUE TITLE
框架结合css transform scale的问题

### ISSUE THREAD

**Issue by a1419735487** [YvesCoding/vuescroll#257]
想用该框架制作类似画布的效果
![image](https://user-images.githubusercontent.com/72694814/124884225-a94fc380-e004-11eb-8d5a-595403c4addb.png)
当scale到一定值时发现问题，左边溢出的部分并没有被识别到，请问有没有解决方案？
![image](https://user-images.githubusercontent.com/72694814/124884603-03e91f80-e005-11eb-973a-ad4831e65740.png)

**Comment by a1419735487** [comment]
同理 上面的溢出部分也不会被识别

**Comment by wangyi7099** [comment]
调用refresh 试试

**Comment by a1419735487** [comment]
> 调用refresh 试试

不行，但是我发现slide模式可以使用鼠标滚轮缩放且不会出现上述问题，更能满足我的需求，非常感谢！
