### ISSUE TITLE
Bounce property

### ISSUE THREAD

**Issue by joingenor** [YvesCoding/vuescroll#262]
In the documentation for vuescroll(slidemode) there is a property for [bouncing ](https://vuescrolljs.yvescoding.org/guide/configuration.html#vuescroll-slide-mode).

There are no documentation of the use and no matter which of the settings i try it does not work. Is this property supposed to work ? If not are there any plans to make it work ?

**Comment by wangyi7099** [comment]
According the the docs, you can set `bouncing`  like below:
```
bouncing: {
        top: 100,
        bottom: 100,
        left: 100,
        right: 100
      },

```

see: https://vuescrolljs.yvescoding.org/guide/configuration.html#overview-7
