### ISSUE TITLE
scrollIntoView second parameter is boolean but it shouldn't

### ISSUE THREAD

**Issue by luisxxor** [YvesCoding/vuescroll#264]
The second parameter of `scrollIntoView` method it is a boolean called `animate`, but then the method calls `scrollBy` with `animate` as the second parameter, but the second parameter of `scrollBy` is the speed and it is numeric

**Comment by wangyi7099** [comment]
Hi. Thanks for the report! The animate's type on docs is a typo. It should be `number` rather than `boolean`.  
And when you are using in real,  when the `animate` you pass is `0` , it means not `animate` , and when you give it a number greater than `0` , it will animate.
