### ISSUE TITLE
Native scrollbar is visible on windows

### ISSUE THREAD

**Issue by bbusch19** [YvesCoding/vuescroll#266]
I'm not sure what the root cause of the issue is, but the windows scrollbar is showing up on my `vuescroll` component. I can't seem to replicate the issue in the provided examples. My container is not a fixed height so I tried using `sizeStrategy: 'number'` but that didn't fix the issue.

![Screen Shot 2021-11-10 at 9 28 13 AM](https://user-images.githubusercontent.com/16787725/141153150-b779d95a-d921-4673-9a36-d20ad6ef2d4a.png)

```javascript
const vueScrollOptions = {
      bar: { keepShow: true, background: 'var(--colors__gray-30)' },
      rail: { background: 'var(--colors__gray-60)', keepShow: true, opacity: 1 },
      scrollPanel: { scrollingY: false, initialScrollX: '100%' },
      sizeStrategy: 'number',
    };
```

**Comment by wangyi7099** [comment]
Hi ! sorry for the late reply! The `sizeStrategy` option is under the `vuescroll`  property!
https://vuescrolljs.yvescoding.org/guide/configuration.html#sizestrategy
