### ISSUE TITLE
scrollbar css not working!!!!! 

### ISSUE THREAD

**Issue by Elham-Ahmadzadeh** [YvesCoding/vuescroll#267]
scroll css not working when I check it on the web: 
but when I use sizeStrategy: 'number' the height exceeds as a loop. As i check class __panel has     overflow: scroll hidden; can someone help me how to remove this issue
  ops: {
        vuescroll: {
          mode: 'native',
          sizeStrategy: 'percent',
          locking: true
        },
        bar: {
          showDelay: 500,
          keepShow: true,
          background: '#FFFFFF',
          opacity: 1,
          hoverStyle: false,
          minSize: 0,
          size: '1%',
          disable: false
        },
        scrollPanel: {
          initialScrollY: false,
          initialScrollX: false,
          scrollingX: true,
          scrollingY: false,
          speed: 300,
          easing: undefined,
          verticalNativeBarPos: 'right'
        },
        rail: {
          background: '#A3ACBC',
          opacity: 0.3,
          size: '1%',
          specifyBorderRadius: '1%',
          gutterOfEnds: '0',
          gutterOfSide: '0',
          keepShow: false
        }
      }

**Comment by wangyi7099** [comment]
Can you elaborate or provide a reproduction?
