### ISSUE TITLE
Vue.prototype is undefined

### ISSUE THREAD

**Issue by Jack-Bailey** [YvesCoding/vuescroll#269]
I run into the error Uncaught TypeError: Vue.prototype is undefined on line 152 of vuescroll.js after installing via yarn. 

Line 152:
```
/* istanbul ignore next */
var isServer = function isServer() {
  return Vue.prototype.$isServer;
};
```
I'm using the exact same code as on the example in the docs. Any suggestions?

**Comment by wangyi7099** [comment]
currently vuescroll only supports vue 2.x

**Comment by Jack-Bailey** [comment]
Thanks for letting me know
