### ISSUE TITLE
Empty CSS rule leading to w3 validator errors

### ISSUE THREAD

**Issue by aoleszek** [YvesCoding/vuescroll#277]
Hello,

I checked my website's code with w3 validation service (https://validator.w3.org/) and noticed some errors related to this scrollbar plugin. It comes out that this plugin is incorrectly setting some CSS properties.

Reported errors:
![image](https://user-images.githubusercontent.com/91440040/160254924-d6a7f4f5-d7f1-409c-9ffc-174a6931360b.png)

Here are the lines I am talking about:
https://github.com/YvesCoding/vuescroll/blob/dev/src/mode/native/native-panel.js#L74

```
// clear legency styles of slide mode...
data.style.transformOrigin = '';
data.style.transform = '';
```
In my opinion it would be a good idea to fix it, to comply with all the standards. Settings those values to nulls instead of empty strings, or CSS keywords `initial`, `unset` may be the solution.

**Comment by wangyi7099** [comment]
Good idea! I will relplace with null in the feature release.
