### ISSUE TITLE
vuescroll inside vuescroll with 90% zoom in chrome

### ISSUE THREAD

**Issue by rotemano** [YvesCoding/vuescroll#278]
Hi team!
I notice a strange issue that happened when my page have scroll inside a scroll on 90% zoom, there is a strange white line that is added to the scroller, here is a print screen of this issue, there is a scroll for all side bar, and for inside tabs too.

![image](https://user-images.githubusercontent.com/23582570/162778337-b6819d4d-f5aa-4a29-aa83-e54d09498439.png)

**Comment by wangyi7099** [comment]
The white line is  part of native scrollbar .

**Comment by wangyi7099** [comment]
Fixed in `4.17.4`
