### ISSUE TITLE
关于内部元素的问题

### ISSUE THREAD

**Issue by whateveryoudo** [YvesCoding/vuescroll#279]
1.__panel容器自带ovrflow:hidden,内部元素使用position：absolute定位的悬浮元素会被隐藏掉（超出部分）。2.vue-scroll下，文字溢出样式无效（__view容器默认为width:fix-content,采用百分比宽度是不生效的。），最后问下 maxHeight,maxWidth 能否支持下百分比。
<img width="640" alt="微信截图_20220517142217" src="https://user-images.githubusercontent.com/30063217/168743322-e57be140-d0d6-4bc2-9edc-6a1acff4781d.png">
<img width="829" alt="微信截图_20220517142256" src="https://user-images.githubusercontent.com/30063217/168743329-95d68d87-5094-4572-bd98-7f739aea1f34.png">
<img width="823" alt="微信截图_20220517142315" src="https://user-images.githubusercontent.com/30063217/168743335-81a0c121-0ff8-4653-8555-0e209a09690a.png">
<img width="233" alt="微信截图_20220517142458" src="https://user-images.githubusercontent.com/30063217/168743336-d041a973-4309-4cee-a369-c055f822f5ba.png">

**Comment by wangyi7099** [comment]
1 悬浮元素的parent dom 可以设置未其他
2 fit content 主要是为了侦测一下dom尺寸发生变化 可以尝试用css样式强制覆盖
3 这个暂不支持 。。 可以也试试用css强制覆盖
