### ISSUE TITLE
源码里提及的网址，现已经被污染

### ISSUE THREAD

**Issue by ColynYu** [YvesCoding/vuescroll#287]
该网址现在为非法网站，被云服务商检测出来，导致自有的域名被封禁，请及时修复更改。
![image](https://user-images.githubusercontent.com/24655091/221737408-b4930d09-8b99-4f45-a632-fd0ce7786c04.png)

**Comment by wangyi7099** [comment]
是哪个版本的

**Comment by ColynYu** [comment]
版本是4.15.0-beta.1，不过我看关闭的issue，在新版有修复这个问题，可能需要考虑升级是否有兼容性问题。
