### ISSUE TITLE
Scroll detection by max-height.

### ISSUE THREAD

**Issue by Vitaliy24** [YvesCoding/vuescroll#29]
Hello, is it possible to make scroll detection by max-height?

**Comment by wangyi7099** [comment]
Hello, thank you for raising an issue first!
And could you tell me what  `Scroll detection by max-height` is? What I guess is  `The way to detect scroll` right? Currently there are tow ways to detect the scroll in vuescroll. They are in the slide mode and the native mode, respectively.

In native mode:
We listen the `onScroll` native event on scroll panel and do the corresponding thing when event triggers.

In slide mode:
We send a `callback` to scroller, and when scroller scrolls, it will invoke the callback, and then do the corresponding thing 
 
But I really don't know how to detect scrolling by `max-height`,  if it's possible, could you give me some tips? Thanks!

**Comment by Vitaliy24** [comment]
I mean, if i need your scroll working, i need to set height: px to parent element.  But if i set max-height instead of height, it doesn't work.

**Comment by wangyi7099** [comment]
OK, you can set `vuescroll`'s property  `sizeStrategy` to `number`, I think will solve your problem. See [hrer](https://wangyi7099.github.io/vuescrolljs/guide/Configuration.html#explanation)

**Comment by Vitaliy24** [comment]
it doesn't work(

**Comment by wangyi7099** [comment]
@Vitaliy24 
Hi I have found this question, And I'm fixing it now, I will give a release a few minuted later.

**Comment by Vitaliy24** [comment]
I solved my problem by setting max-height style class to .vuescroll-panel, but it's 'fast solution', still waiting for your fix :) Thank you!

**Comment by wangyi7099** [comment]
@Vitaliy24 
Hi Have just released 4.5.23, could you please have a try whether solve your problem or not?

**Comment by wangyi7099** [comment]
@Vitaliy24 
Hi! This problem is closed first. If you have any questions, please feel free to comment again!

**Comment by Vitaliy24** [comment]
Upadte made it worse( Now if i have propery 'max-height', it sets height 0 to my container.

**Comment by wangyi7099** [comment]
@Vitaliy24 
Could you please give me a reproduce repo?

**Comment by wangyi7099** [comment]
If you want your `vuescroll` work, make sure to follow the following tow points:
1. Update to the latest version. Now the latest version is `4.5.31` and fix some bugs.
2. If your parent dom is not a fixed size , such as `max-height` or something else, please try to set  `sizeStrategy` to `number`. Like so:
```javascript
   ops: [
       vuescroll: {
            sizeStrategy: 'number'  
      }
  }
```

**Comment by borovez** [comment]
I cannot get maxHeight to work either, it is driving me nuts...

My vuscroll version is **4.16.1**

My vue component template:
```
<div class="relative overflow-auto">
    <vuescroll :ops="ops">
        <slot name="content" />
   </vuescroll>
</div>
```
My options are set as:
```
ops: {
        maxHeight:200,
        vuescroll: {
          sizeStrategy: 'number',
        },
}
```

**Comment by jh-digical** [comment]
@borovez it also drove me nuts today, the maxHeight notes in the docs is misleading, the correct way to use maxHeight is to set it in the scrollPanel, example:

`scrollPanel: { maxHeight: 500 },`

i got it working by trial and error since the example in the docs' maxheight is working so I was really wondering how it's being used

**Comment by jh-digical** [comment]
@wangyi7099 please update the maxHeight notes in the docs. Thank you.
