### ISSUE TITLE
Request for @types support

### ISSUE THREAD

**Issue by Luluno01** [YvesCoding/vuescroll#40]
~~**Is your feature request related to a problem? Please describe.**~~
~~A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]~~

**Describe the solution you'd like**
~~A clear and concise description of what you want to happen.~~

Some `.d.ts` files would be appreciated.

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

An alternative I have considered is writing those files by myself and open a pull request, which is not gonna happen.

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

Actually you can reply to this issue in Chinese if you like.

**Comment by wangyi7099** [comment]
Hi! #28 also referred this issue,  ok, I will work on it, and add a `.d.ts` file soon , maybe in next release.

**Comment by Luluno01** [comment]
@wangyi7099 Oh I thought I was the very first one to open an issue of this repo. Looks like I've missed some closed issues XD.

Looking forward to next release.

Greate thanks!

**Comment by wangyi7099** [comment]
Hello, this feature has been address in `4.6.11`, you can try it now!

**Comment by Luluno01** [comment]
@wangyi7099 Appreciate! It's been just few hours. Quite amazing.
