### ISSUE TITLE
使用NUXT 服务端渲染时 报DOM错误

### ISSUE THREAD

**Issue by denkloge** [YvesCoding/vuescroll#42]
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

配置如下：
{ src: '~plugins/vuescroll', ssr: false },
ssr 是false

这个问题是因为服务端与客户端渲染的DOM结构不一样。出现的这个问题是vuescroll没有允许在服务端使用导致的。 

但是如果改成true 就会报 window is not defined
因为服务端没有window

**Comment by wangyi7099** [comment]
你好， 请先看下#38，
我先研究一下nuxt， 今晚会答复你。

**Comment by denkloge** [comment]
@wangyi7099 非常感谢！看过#38了。跟我这一样 但是他没有发现报DOM错误  这样的话 本地测试虽然好用，但是部署到正式会报错的

**Comment by wangyi7099** [comment]
嗯嗯！ 好的！ 我现在工作正忙， 晚上研究一下， 然后再答复你！

**Comment by wangyi7099** [comment]
找到原因了， 你的`vuescroll`需要用`no-ssr`包裹起来，像这样：
```html
 <no-ssr>
   <vue-scroll>
       <!-- Your Content -->
  </vue-scroll
</no-ssr>
```
我的建议是，注册一个全局的组件`vs-ssr`，像这样：
```javascript
   Vue.component('vs-ssr', {
        render(h) {
         return {
             h('no-ssr', [
                h('vuescroll', this.ops, this.$slots.default) 
            ])
         }
       }
  })
```
当然也可以用单文件组件的方式， 具体怎么样还是看你的选择， 这个issue就先关了。

**Comment by denkloge** [comment]
@wangyi7099 确实好用，非常感谢！！！

**Comment by wangyi7099** [comment]
@denkloge 
多谢提供的建议～ 好的 我去看一下！！

**Comment by wangyi7099** [comment]
已经支持ssr了。 4.7.0

配置plugin的时候
{ src: '~plugins/vuescroll'}, // ssr选项 可以不必设置为true
