### ISSUE TITLE
在使用vuescroll之后,部分ui控件就不能自适应了,例如element-ui的table

### ISSUE THREAD

**Issue by Abigale-ztg** [YvesCoding/vuescroll#43]
在用vuescroll之后,element-ui的table控件宽度无法自适应,只要宽度变小,就会出现横向滚动条

**Comment by wangyi7099** [comment]
去掉vuescroll是否可以自适应呢？

**Comment by Abigale-ztg** [comment]
去掉的话,是可以自适应的

**Comment by wangyi7099** [comment]
【只要宽度变小】
这个【只要宽度变小】 能否给我描述一下具体的场景？ 我回去重现下。

**Comment by Abigale-ztg** [comment]
就是调整浏览器大小的时候,浏览器窗口大小发生变化.

**Comment by wangyi7099** [comment]
你的父级div的宽度是百分比是吗？  如果是百分比的话， 试下把`sizeStrategy` 设置为 `number`试下
```javascript
   ops: {
    vuescroll: {
         sizeStrategy: 'number'
    }
  }
```

如果不行 能否提供一个最小化的重现版本 让我更好的定位bug

**Comment by Abigale-ztg** [comment]
还有就是
vuescroll-content里width: -webkit-fit-content; 样式设置导致子dom的宽度大于我父dom设置的宽度,我子dom设置的宽度为100%

**Comment by Abigale-ztg** [comment]
我把
![image](https://user-images.githubusercontent.com/20549093/42502725-667542aa-8469-11e8-8a21-5f1f952a2e26.png)
这个样式取消之后就可以自适应了,不知道取消这个样式,是否有其他的影响

**Comment by wangyi7099** [comment]
好吧  你可以把这个样式覆盖掉了， 这个样式主要是为了使宽度和子元素保持一致。           具体的情况我也不太清楚。

**Comment by leaper1** [comment]
css 应该增加
`.__vuescroll .__view {
  max-width: 100%;
}`
这样才能自适应

**Comment by kunwei-kooboo** [comment]
@wangyi7099 , consider adding this `.__vuescroll .__view { max-width: 100%; }` for next version?

**Comment by wangyi7099** [comment]
> consider

这样的话就不能监测内容的resize事件了。
