### ISSUE TITLE
How to use it in AMD project

### ISSUE THREAD

**Issue by DLJames** [YvesCoding/vuescroll#44]
**Describe your feature, thanks!**
我想在我的dojo项目里引用组件，但是define进来并不能很好地使用，控制台报不能找到vue.js错误，我已经引用了vue.js。而且我的vue和vuex都是这样引用的，都运行的很好。
(I want to use this component in my Dojo (based on AMD) project, but I download the vuescroll.js and vuescroll.min.js and define it, but can not use it correctly, it will give me an 404 error, can not find vue.js)

**What does this feature solve?**
所以能不能提供一个可以在AMD标准下能用的组件啊，谢谢
So, could you please offer a version can  be used in AMD project, like vue,min.js, vuex.min.js, they work well in Dojo, thanks.

**Comment by wangyi7099** [comment]
刚看了下vuex 发现 vuex的源码是不依赖vue的， 也就是说你得手动use安装一下， 而vuescroll是自动判断当前环境是否存在vue的，自动帮你安装，不需要手动use， 也就是说是依赖vue的。

**Comment by wangyi7099** [comment]
测试下elementui有没有这个问题？
Do you such  problem with element-ui?

**Comment by wangyi7099** [comment]
最好能给我一个重现的demo方便我查看。
