### ISSUE TITLE
Should remove "import vue from 'vue'" from source code and in package.json use peerDependencies vue

### ISSUE THREAD

**Issue by lijing666** [YvesCoding/vuescroll#45]
**Your config**

**Your Workaround**

- Browser:

- Vuescroll Version(Try to update to the latest version may solve your problem):

- OS:

**What happened?**
When build with webpack, vuescroll may self contained vue in its packed module,this is wrong.
Vuescroll as a plugin for Vue,just should has an install method with Vue as parameter is enough.But I saw ` import vue from 'vue'` in the index.js from the source.For the problem ` import vue from 'vue'` should be removed from the source code and in package.json use 
`"peerDependencies": {
    "vue": "^2.5.16"
  },` instead.

**Comment by lijing666** [comment]
@wangyi7099 哈哈，我用中文描述吧，Vuescroll入口的页面写了import vue from vue 然后package.json又定义了dependencies依赖vue是不合适的，因为这样的话，webpack打包会随着Vuescroll把vue也打进去的，造成重复引用，作为Vue的插件，提供install插件接口就好了，不需要import vue进去，也不用强制写个dependencies，用peerDependencies指定依赖要求就好了

**Comment by wangyi7099** [comment]
谢谢 ， 我认为是可以移除掉的。 关于打包， 这个打包工具用的是rollup，声明了Vue为第三方库。并不会打包进去。
