### ISSUE TITLE
Issues after update

### ISSUE THREAD

**Issue by vinayakkulkarni** [YvesCoding/vuescroll#47]
**Your config**
Default config

**Your Workaround**
Roll back to previous version

- Browser:
Chrome Version 67.0.3396.99

- Vuescroll Version(Try to update to the latest version may solve your problem): 4.7.0

- OS: macOS High Sierra 10.13.6

**What happened?**
Started to get `console.warn()`
```js
[vuescroll] The options: vRail, hRail, vBar, hBar have been deprecated since v4.7.0,please use corresponing rail/bar instead!
```

PS. All the demo links and Documentation seems to be dead.

**Comment by aldinezi** [comment]
@vinayakkulkarni console warns are not an issue. 
I can also confirm that documentation links are down. 
As soon as it's back online, you should replace your options with new ones.

**Comment by wangyi7099** [comment]
Hi sorry for the server is dead! It seems that something is wrong about DNS, I have just fix it, and the server is working on.

As for `hRail, vRail, hBar, vBar` , I think few people use different options between vertical and horizontal, so I just change the strategy to `set bar/rail to work to both vertical and horizontal`...
