### ISSUE TITLE
Auto scroll on load

### ISSUE THREAD

**Issue by Humeira** [YvesCoding/vuescroll#50]
Hello,

I'm testing out VueScroll for a project I am currently working on to see if it fits. All is well, except I can't seem to find how to auto scroll to bottom of a div on component initialisation.

Is this possible? If yes, how?

Thank you.

This is my config : 

```
      ops: {
        vuescroll: {
          mode: "native"
        },
        scrollPanel: {
          intialScrollY: true,
          intialScrollX: true,
          scrollingX: true,
          scrollingY: true,
          speed: 300
        }
      }
```

**Comment by wangyi7099** [comment]
Hello, you can set `intialScrollY(X)` to `100%` to auto scroll to bottom when component is mounted.
```javascript
ops: {
        vuescroll: {
          mode: "native"
        },
        scrollPanel: {
          intialScrollY: '100%', //true,
          intialScrollX: '100%', //true,
          scrollingX: true,
          scrollingY: true,
          speed: 300
        }
      }
```

**Comment by Humeira** [comment]
@wangyi7099 

Thanks for your prompt response. I just tried this, it didn't work.

**Comment by wangyi7099** [comment]
@Humeira  

I'm sorry for this. It's a typo in document...
The option should be this:
```javascript
ops: {
        vuescroll: {
          mode: "native"
        },
        scrollPanel: {
          initialScrollX: '100%', //true,
          initialScrollX: '100%', //true,
          scrollingX: true,
          scrollingY: true,
          speed: 300
        }
      }
```

**Comment by Humeira** [comment]
@wangyi7099 

Hello,

Hmm now it's just two initialScrollX and it doesn't work. 

This one does 

```
        scrollPanel: {
          initialScrollY: '100%', //true,
          scrollingX: true,
          scrollingY: true,
          speed: 300
        }
```
Anyway, thanks mate I really appreciate the quick replies! 👍
