### ISSUE TITLE
handle-scroll-complete event not triggered

### ISSUE THREAD

**Issue by li781825965** [YvesCoding/vuescroll#53]
我用的doc里面codepen的demo，在chrome 61运行，无法触发handle-scroll-complete事件

**Comment by wangyi7099** [comment]
额 doc codepen里的demo的代码都是老版本的了。。 没有添加css样式 
handle-scroll-complete 需要在本地自己试一下了。或者在codepen里自行添加css样式。

**Comment by li781825965** [comment]
哦，可是触发事件和css有什么关系呢？我在本地是最新的4.7.4的版本，可是还是没触发o(╥﹏╥)o

**Comment by wangyi7099** [comment]
需要引入 vuescroll的的css文件呀。 以前老的codepen里面没引入vuescroll.css。 导致了没有样式附加的问题。 具体请看[这里](http://vuescrolljs.yvescoding.org/zh/guide/getting-started.html#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)。


You need to introduce vuescroll's CSS file. In the old codepen, vuescroll.css was not introduced. This leads to problems with no style attach. See [here] (http://vuescrolljs.yvescoding.org/guide/getting-started.html#quick-start).

**Comment by wangyi7099** [comment]
再试试 
我已经手动把这条
```html
<link rel="stylesheet" href="https://unpkg.com/vuescroll/dist/vuescroll.css">
```
添加上了。

Try again

I have manually done this.

```html

<link rel= "stylesheet" href= "https://unpkg.com/vuescroll/dist/vuescroll.css" >
```
Add it up.

**Comment by li781825965** [comment]
看到了，谢谢！但是我发现如果不是鼠标指针拖动滑条，而是滚轮操作的话，好像还是不会触发此事件，是吗？

**Comment by wangyi7099** [comment]
是的  滚动触发的话需要监听handle-scroll事件了。。  而且也不好判断什么时候操作完成了。 所以没加

Yes, scrolling triggers need to detect handle-scroll events. And it's not easy to tell when the operation is finished. So it doesn't add

**Comment by li781825965** [comment]
嗦嘎，3QQQ
