### ISSUE TITLE
OffsetTop of element inside scroll

### ISSUE THREAD

**Issue by Vitaliy24** [YvesCoding/vuescroll#55]
Hello, is it possible to get offsetTop of element inside vuescroll? When i trying to get offsetTop, it's always give 0.

**Comment by Vitaliy24** [comment]
No. Not the vue-scroll element. I need position of element INSIDE vuescroll.

**Comment by wangyi7099** [comment]
Can you give me the example you have tried?

**Comment by Vitaliy24** [comment]
Nevermind, sorry.

**Comment by wangyi7099** [comment]
Closing due to no more reply.
