### ISSUE TITLE
vue低版本不能用么?

### ISSUE THREAD

**Issue by YuFy1314** [YvesCoding/vuescroll#56]
![](https://user-images.githubusercontent.com/24446694/44768853-40c61400-ab95-11e8-823a-90c9fe361ec5.png)
@wangyi7099 我们项目中的vue是2.2.6版本的, 安装完了vuescroll依赖说是不支持? 这个问题该怎么解决?

**Comment by YuFy1314** [comment]
@wangyi7099   那我这个问题应该怎么解决呢? 还是说再安装一个vuescroll的低版本?

**Comment by YuFy1314** [comment]
@wangyi7099  我刚刚在npm上看到了你这个有211个版本包, 安装哪一个才适合我这个情况呢  也就是vue2.2.6的

**Comment by wangyi7099** [comment]
直接用就行 不用管警告 稍后我会把依赖版本改成正确的。

**Comment by wangyi7099** [comment]
Close via https://github.com/YvesCoding/vuescroll/commit/35e04162bc39b0207fa418f316454f0135cb7b76
