### ISSUE TITLE
<vue-scroll>还需要自己注册?

### ISSUE THREAD

**Issue by YuFy1314** [YvesCoding/vuescroll#57]
Unknown custom element: <vue-scroll> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
@wangyi7099  这个插件怎么注册呢? 你的API里没有提到, 望大佬指点

**Comment by YuFy1314** [comment]
我是手动引的vuescroll.min.js

**Comment by wangyi7099** [comment]
在[这里](http://vuescrolljs.yvescoding.org/zh/guide/getting-started.html#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B), 引入完组件和CSS之后 Vue.use一下即可

**Comment by YuFy1314** [comment]
@wangyi7099  我已经use了, 只不过没有引入css, 因为我安装的是vuescroll 3.3.2的版本的
![](https://user-images.githubusercontent.com/24446694/44776831-94435c80-abab-11e8-8120-45dbc7104dde.png)
![](https://user-images.githubusercontent.com/24446694/44776860-ab824a00-abab-11e8-98d1-c62280b09cdd.png)
![](https://user-images.githubusercontent.com/24446694/44776888-ba68fc80-abab-11e8-9c74-fe2e47d56e77.png)

**Comment by wangyi7099** [comment]
@YuFy1314  安装最新版的也没事。 这个版本我都忘了。。 不知道有没有bug 还是安装最新版本的吧。。

**Comment by YuFy1314** [comment]
@wangyi7099  刚刚安的新版本出了问题, 现在修复了??

**Comment by wangyi7099** [comment]
刚才你截图那个问题 没事 不影响功能的。

**Comment by YuFy1314** [comment]
好的   我现在正在安装新版本, 我再试试哈
