### ISSUE TITLE
怎么弄上下三角形箭头

### ISSUE THREAD

**Issue by YuFy1314** [YvesCoding/vuescroll#58]
@wangyi7099  我看API就是改成native像下面这样不就可以了么??  我这个为什么不好使
![](https://user-images.githubusercontent.com/24446694/44828482-ab855700-ac4a-11e8-8206-dda03babd2ab.png)
![](https://user-images.githubusercontent.com/24446694/44828531-e8e9e480-ac4a-11e8-8b30-e4de59c71508.png)

**Comment by wangyi7099** [comment]
什么上下三角箭头  这跟vuescroll没有关系吧。。。

**Comment by YuFy1314** [comment]
对不起, 是我描述的不够详细, 就是弄成这个样子的
![](https://user-images.githubusercontent.com/24446694/44828825-2ef37800-ac4c-11e8-9346-f22434789ad7.png)

**Comment by wangyi7099** [comment]
额。。 这个功能暂时还没有

**Comment by YuFy1314** [comment]
@wangyi7099  好的吧   感谢您的回答, 有了那个其实很丑, 但是需求里要求的,  哎...

**Comment by wangyi7099** [comment]
你问他滚动条两端是圆的行不行  比那两个箭头好看多了。

**Comment by wangyi7099** [comment]
咦...  你的滚动条两端为什么不是圆的? 我设置了border-radius属性啊

**Comment by YuFy1314** [comment]
@wangyi7099    长什么样子呢, 可以发个截图么? 对了  我想更改滚动条的border-radius, 只能通过js或者important更改么? 比如说配置里有没有方法可以更改呢?

**Comment by wangyi7099** [comment]
你看这些[Demo](http://vuescrolljs.yvescoding.org/zh/demo/#_1-%E5%9F%BA%E7%A1%80%E6%BB%9A%E5%8A%A8)滚动条两端都是圆的啊。。 为什么你的看起来不是圆的呢？

**Comment by YuFy1314** [comment]
哈哈  需求太怪异, 哪里丑往哪里改, 哎  好坑啊  
我的滚动条被我改了

**Comment by wangyi7099** [comment]
哈哈

**Comment by YuFy1314** [comment]
@wangyi7099    您还没有告诉我那个border-radius可以改不,  还是说可以更改的东西只有API配置里的那几个???

**Comment by wangyi7099** [comment]
@YuFy1314  哦哦 不好意思- - 。 
> 那个border-radius可以改不
可以啊 ， 本来就是有border-radius， 可以改成圆的方的， 你可以用CSS样式覆盖。

**Comment by YuFy1314** [comment]
@wangyi7099  我们这个项目为了便于维护, 所以不能用js写, 也就是只能用css来解决, 但是你的这个是行内样式, 我后面覆盖不了, 下面这样写就覆盖不了:
![](https://user-images.githubusercontent.com/24446694/44840536-d0da8b00-ac73-11e8-97eb-a8a4ec0f6340.png)
我目前想到的解决方案是important:
![](https://user-images.githubusercontent.com/24446694/44840579-e780e200-ac73-11e8-990c-fd904651162d.png)
important的这个方法虽然好使, 但是如果其他地方再用到这个vuescroll的话, 这个border-radius等样式就全都覆盖了, 所以还有没有其他的解决方案呢?

**Comment by wangyi7099** [comment]
@YuFy1314 
Border-radius 为什么要设置覆盖成`0`呢？那样不久变成方的了吗？目前来将 `bar: {}` 中还没有关于border-radius 的配置。 你如果需要的话可以提个PR啥的= =

**Comment by YuFy1314** [comment]
哎, 这个鬼需求让做成方的, @wangyi7099 行, pull request大约等多久能做好呢?

**Comment by wangyi7099** [comment]
@YuFy1314  你有没有时间来做？

**Comment by YuFy1314** [comment]
我也可以做么? 这要怎么做? 我不会具体操作呀? 需要你的指点

**Comment by wangyi7099** [comment]
@YuFy1314 
先在  
https://github.com/YvesCoding/vuescroll/blob/35e04162bc39b0207fa418f316454f0135cb7b76/src/shared/global-config.js#L31
添加对应的配置。

然后在
https://github.com/YvesCoding/vuescroll/blob/dev/src/mode/shared/bar.js

中 实现相应的功能即可

**Comment by YuFy1314** [comment]
如何才能在您的这个分支上更改代码  苦笑    被自己蠢笑了

**Comment by wangyi7099** [comment]
@YuFy1314 
你好 fork 我这分支以后修改代码， 然后提交PR即可。

**Comment by YuFy1314** [comment]
好的, 万分感谢,我这就去试试

**Comment by YuFy1314** [comment]
您的代码里是这么写的: borderRadius: vm.ops.rail.size
那我就直接把后面的删掉, 然后手动给一个值就可以了吧

**Comment by wangyi7099** [comment]
加我QQ兄弟 724003548  issue里不适合聊这个， 会打扰到watch的人。

**Comment by YuFy1314** [comment]
好的ヽ(￣▽￣)و
