### ISSUE TITLE
Horizontal scroll without shift key

### ISSUE THREAD

**Issue by NaumovEvgeniy** [YvesCoding/vuescroll#60]
Hi! Thanks for a good plugin, it's realy good. 

But I have a problem with horizontal scroll. Me need scroll horizontal content without shift key? Is it possible? 

I didn't see a need parameter in the docs

**Comment by wangyi7099** [comment]
Hi!  currently there is not a proper way to do with horizontal scroll , because we move native scrollbar by reacting the native scroll event. IMO, you can listen to an event, and use `scrollTo` api to scroll the content. e.g. 
You can listen to a keyboard event and use
```javascript
    this.$refs.vs.scrollTo({x: '5%'});
```
to scroll content.

**Comment by NaumovEvgeniy** [comment]
@wangyi7099 are you going to add this feature in the future?

**Comment by wangyi7099** [comment]
@NaumovEvgeniy 
Perhaps not ... because you can simply implement it yourself.
