### ISSUE TITLE
 4.8.0 版本报错

### ISSUE THREAD

**Issue by btdf007** [YvesCoding/vuescroll#62]
TypeError: Cannot read property 'vuescroll' of undefined  

![image](https://user-images.githubusercontent.com/1208514/44967978-9aed1d80-af77-11e8-9b4b-7e967e36426b.png)

**Comment by wangyi7099** [comment]
您好，能否提供一下能够重现次问题的代码? 我这边是没有问题的。 或者重启下服务试试。

**Comment by stevepop** [comment]
Is there a work-around we can use in the meantime? We are using this in our project and it is broken at the moment due to the error shown above.

**Comment by wangyi7099** [comment]
@stevepop 
Hi This bug has been fix in `4.8.2`
https://github.com/YvesCoding/vuescroll/commit/91d81e759c0e2de8f06868cafe548fc242c6ed4f

**Comment by stevepop** [comment]
@wangyi7099 Thanks, will up-date to that!
