### ISSUE TITLE
上拉加载

### ISSUE THREAD

**Issue by piapple** [YvesCoding/vuescroll#63]
版本"vuescroll": "^4.8.1"

我每个页面都有一个slide模式的vuescroll
可是我每次切换页面 都无法上拉加载，
我在mounted中调用refresh()有时候能正常上拉，有时候不能

**Comment by piapple** [comment]
我给的100%，滑动是可以的，但是到上拉加载就无效了

**Comment by wangyi7099** [comment]
[试试](http://vuescrolljs.yvescoding.org/zh/guide/configuration.html#vuescroll)把`sizeStrategy`设置为`number`
