### ISSUE TITLE
RTL issue!

### ISSUE THREAD

**Issue by Rux77** [YvesCoding/vuescroll#64]
First, thank you for a this plugin.

When using it on an RTL page ( direction: rtl; ), It shows tow scrollbars! one on the **left**, and one on the **right** ( which is the correct scrollbar for RTL pages )

I took a screenshot of the issue:
![image](https://user-images.githubusercontent.com/27288465/45000762-52ae1980-afd0-11e8-9d9b-8389e2bc5cd6.png)

how to remove the scrollbar on the left side?

**Comment by wangyi7099** [comment]
I'm curious about that in mose cases the native scrollbar is on the right, so I don't think about the case that scrollbar on the right. FYI, why your scrollbar is on the left ? Can you explain a little to me ? Thanks!

**Comment by wangyi7099** [comment]
Try `4.8.2` may solve your problem.
