### ISSUE TITLE
滚动条不能鼠标拖动

### ISSUE THREAD

**Issue by hametan** [YvesCoding/vuescroll#69]
滚动条不能鼠标点击拖动，只能滚轮，不知道是需要配置还是我使用方式不对，还是本身就是一个BUG

**Comment by wangyi7099** [comment]
刚才试了下  能拖动。 配置也没有能影响拖动拖动的， 能否提供一个重现bug的代码或者项目 ?

**Comment by hametan** [comment]
http://vuescrolljs.yvescoding.org/  就不行，我试过CHROME 65,火狐61.0.2，maxthon 5.2.4.2000，都不行，有换过两台电脑试，都是chrome 65，均不能。

**Comment by wangyi7099** [comment]
刚才试了下  windows和mac os 都没问题 能否录一小段视频 我看看你是怎么拖动的？

**Comment by hametan** [comment]
见附件

**Comment by hametan** [comment]
http://m.qpic.cn/psb?/V11yXmhA2JQ7I5/hQxfIJBHozuI82FMaEhbOirX5KuMjx1Ly6XZ6L.c.Wc!/b/dDYBAAAAAAAA&bo=UAWoAgAAAAACV4w!&rf=viewer_4

**Comment by hametan** [comment]
问题见下图：
http://m.qpic.cn/psb?/V11yXmhA2JQ7I5/hQxfIJBHozuI82FMaEhbOirX5KuMjx1Ly6XZ6L.c.Wc!/b/dDYBAAAAAAAA&bo=UAWoAgAAAAACV4w!&rf=viewer_4

**Comment by wangyi7099** [comment]
你好 测试了几台电脑之后 都是可以的 这个issue就先关了。

**Comment by hametan** [comment]
我今天又测试了一下，感觉是我电脑的问题？远程连接其它电脑一样存在这种问题，远程连接的电脑本身没有问题。

**Comment by wangyi7099** [comment]
哈哈 估计是你电脑的问题吧。

**Comment by hametan** [comment]
测试了很多种可能性，现在我在想是不是小屏幕的问题，我的屏幕是12.5

**Comment by wangyi7099** [comment]
我想应该不是的。 手机上也能拖动。

**Comment by hametan** [comment]
好吧，只有等WIN10秋季更新出来了，重装下系统看看了。
