### ISSUE TITLE
Window resize event

### ISSUE THREAD

**Issue by GitNomster** [YvesCoding/vuescroll#71]
I have such problem:
I've imported vuescroll globally, then go to the component, where i'm using vuescroll, then go back (component with vuescroll is destroyed), but 'window-resize' event still active. When i go to the component with vuescroll and back again - 'window-resize' event doubled (on 1 pixel move it fires twice) and so on.

**Comment by wangyi7099** [comment]
Thanks for pointing it out. It is going to be fized in next minor release.
