### ISSUE TITLE
初次进入页面BUG

### ISSUE THREAD

**Issue by sh0ckey** [YvesCoding/vuescroll#83]
第一次进入页面，绑定window的resize事件，在销毁时移除失败，导致resize事件内执行取不到对应dom报错
```
//绑定
window.addEventListener('resize', handleWindowResize.bind(this), false);
//解绑 
window.removeEventListener('resize', handleWindowResize, false);
```
绑定函数由于改变了上下文指向，与解绑函数不一样导致初次进入页面解绑失败，刷新是正常的，具体原因不明，但是我的真机上会报错，去除bind(this)后，正常

**Comment by wangyi7099** [comment]
Closing due to having been fixed in 4.9.X
