### ISSUE TITLE
@handle-scroll event function with `this` null

### ISSUE THREAD

**Issue by ArchOrn** [YvesCoding/vuescroll#85]
Hi,

I am currently trying to use your library to add, when the user reaches 90% of the horizontal scroll, some new items, to simulate an infinite scroll. I tried first the `load-start` event without success, but then I tried the `handle-scroll` event.

```
<vue-scroll ref="scroller" class="vue-scroll" :ops="ops" @handle-scroll="handleScroll" @click.native="handleClick">
...
```

I am using Typescript in my project, and so I have my component as a class:

```
export default class Slider extends Vue {
    @Prop() public loadMore!: () => void;

    public $refs!: {
      scroller: any,
    };

    private ops: any = {
      vuescroll: {
        zooming: false,
        scroller: {
          boucing: false,
        },
      },
      scrollPanel: {
        scrollingY: false,
      },
      bar: {
        background: '#9CCC65',
      },
    };

    public loading: boolean = false;

    ...

    public handleScroll(vertical: any, horizontal: any) {
      console.log(`vertical: ${JSON.stringify(vertical)}, horizontal: ${JSON.stringify(horizontal)}`);
      console.log(`this: ${this}`);
      console.log(`loading: ${this.loading}`);
      if (horizontal.process > 0.9 && !this.loading) {
        this.loading = true;
        this.loadMore();
        this.loading = false;
      }
    }

    public handleClick(param1: any, param2: any) {
      console.log(`this: ${this}`);
    }
  }
```

My problem is that I cannot access the `loading` data inside my `handleScroll` method, because `this` is null:
`Error in event handler for "handle-scroll": "TypeError: Cannot read property 'loading' of null"`
To check, I tried with the native `onClick` event and `this` is correctly referenced. Is there something I am doing wrong?

Thank you.
Best regards,

Raphaël

PS: the version I am using is: `4.9.0-beta.8`

**Comment by wangyi7099** [comment]
Hi . I think you should bind `handleScroll ` to `this `. Because `handleScroll ` is not `methods` of Vue, and won't be bound by Vue, so you should bind yourself.  I'm not familiar with `class-type` written, so I can give you much help, sorry~

**Comment by ArchOrn** [comment]
Hi,

Thank you for your quick answer :) I will look into that, and post here my findings if I succeed.

Have a nice day,

Raphaël

**Comment by ArchOrn** [comment]
Hi, I finally succeeded in doing what I wanted. For the people who want to do the same:

Inside the template
```
<vue-scroll ref="scroller" class="vue-scroll" :ops="ops" @handle-scroll="handleScrollBound">
[...]
```

Inside the typescript class
```
public handleScrollBound = this.handleScroll.bind(this);
public handleScroll(vertical: any, horizontal: any) {
  if (horizontal.process > 0.9 && !this.loading) {
    this.loading = true;
    this.loadMore();
    this.loading = false;
  }
}
```

Hope this helps :)
