### ISSUE TITLE
滚动条默认隐藏的时候，能否实现鼠标移动到滚动内容区域的时候显示出来？

### ISSUE THREAD

**Issue by BruinY** [YvesCoding/vuescroll#87]
滚动条默认隐藏的时候，能否实现鼠标移动到滚动内容区域的时候显示出来？而不是在滚动的时候才显示。

**Comment by wangyi7099** [comment]
能  把onlyShowWhenScroll 设置为  false 就好了，具体请看bar习惯的配置吧。
