### ISSUE TITLE
Scrollbar can be too small to handle

### ISSUE THREAD

**Issue by kaiserkiwi** [YvesCoding/vuescroll#89]
If there are too many entries in a container, the scrollbar can be so small, that you can barely see and handle it. There should be a minimal size or even better a setting for this.

If I try to solve this with a `min-height` then the scroll bar leaves the rail when I scroll further down because of the Animation handling with `transform`.

In my case the automatic height of the bar is just 0.535489%.

**Comment by wangyi7099** [comment]
Well, a lot of people occurred the same issue too, I think we should fix it in next beta version.
