### ISSUE TITLE
How do you think vuescroll docs?

### ISSUE THREAD

**Issue by wangyi7099** [YvesCoding/vuescroll#90]
Any suggestion? Thanks !

**Comment by MissMukmuk** [comment]
初始化会先显示原生的滚动条

**Comment by wangyi7099** [comment]
> 初始化会先显示原生的滚动条

需要一个重现的demo

**Comment by dzm504** [comment]
父元素设置max-height怎么使用呢？？

**Comment by MissMukmuk** [comment]
> > 初始化会先显示原生的滚动条
> 
> 需要一个重现的demo

可以说下具体重现怎么写吗?谢谢

**Comment by wangyi7099** [comment]
> > > 初始化会先显示原生的滚动条
> > 
> > 
> > 需要一个重现的demo
> 
> 可以说下具体重现怎么写吗?谢谢

你好，写一份能重现bug的代码上传到github就可以了

**Comment by squareGuo** [comment]
安装一直报错。。。。。

**Comment by Amelia608** [comment]
事件:handle-scroll-complete滚动到底未触发

**Comment by 13775906336** [comment]
在chrome浏览器，vuescroll所在的元素如果宽度为 XXX.5Xpx  右侧就会出现一条白线

**Comment by 13775906336** [comment]
> 在chrome浏览器，vuescroll所在的元素如果宽度为XXX.5Xpx右侧就会出现一条白线

![image](https://user-images.githubusercontent.com/30690773/57353116-0d16a180-719a-11e9-9d37-b0fde7f7744b.png)
找到原因是这个_panel的marginRight 一样的代码一会-15一会-17，-15的时候就换有一条白线，难受，找不到为什么

**Comment by wangyi7099** [comment]
> > 在chrome浏览器，vuescroll所在的元素如果宽度为XXX.5Xpx右侧就会出现一条白线
> 
> ![image](https://user-images.githubusercontent.com/30690773/57353116-0d16a180-719a-11e9-9d37-b0fde7f7744b.png)
> 找到原因是这个_panel的marginRight 一样的代码一会-15一会-17，-15的时候就换有一条白线，难受，找不到为什么。中间升级了一下版本 不知道是不是这个原因

能说下是什么操作系统 环境浏览器版本等问题吗。。

**Comment by sandy-shi** [comment]
页面有3个组件都用了插件之后，在页面刷新或者resize的时候，3个滚动条会同时出现闪烁一下，然后再消失

**Comment by wangyi7099** [comment]
> 页面有3个组件都用了插件之后，在页面刷新或者resize的时候，3个滚动条会同时出现闪烁一下，然后再消失

这是预期的行为 。 页面刷新或者refresh时会调用 updateBar 然后更新bar的状态 然后显示一下滚动条再隐藏。

**Comment by punghunger** [comment]
请问，浏览器环境里面，拖拽滚动条内容不滚动，是怎么回事呀
