### ISSUE TITLE
How can I fix the scroll button to the buttom

### ISSUE THREAD

**Issue by tlmcasper** [YvesCoding/vuescroll#93]
Hi, 

I am using the vuescroll and meet a problem.

I use css overflow-y:hidden to disable system scroll bar and use below javascript to let content scrolls to the bottom:
        document.body.scrollTop = document.body.scrollHeight

It works fine without vuescroll, but when I use vuescroll to include my scrolling content, the scroll bar will show up, but scroll to bottom will not work.

<div class="item-list">
    <ul id="parent" >
      <vue-scroll :ops="ops">
        <li class="new-item" v-for="item in items" v-on:click="onclick">
          {{item.text}}
        </li>
      </vue-scroll>
    </ul>      
  </div>

could you please tell me how can I fix the scroll button to the bottom?

**Comment by wangyi7099** [comment]
Hi you can use `scrollTo` api to scroll to button.
```html
<vue-scroll ref="vs">
//... content
</vue-scroll>
```
```javascript
this.$refs['vs'].scrollTo({y: '100%'})
```

**Comment by wangyi7099** [comment]
hi im going to close this as it is resolved. :)
