### ISSUE TITLE
按键盘的上下左右键会触发滚动条，但跟自定义的键盘事件冲突。

### ISSUE THREAD

**Issue by bolerole** [YvesCoding/vuescroll#94]
如题，能否对vue-scroll的键盘事件加个配置项？否则即触发了vue-scroll的滚动事件又触发了自定义事件

**Comment by wangyi7099** [comment]
好的 我要出一个配置项。。 
```javascript
{
  vuescroll: {
    nativeScrollDisable: false
 }
} 
```
然后你按键盘前可以先设置为`true`等做完某些操作再设置回`false`.

**Comment by wangyi7099** [comment]
好的 我要出一个配置项。。 
```javascript
{
  vuescroll: {
    nativeScrollDisable: false
 }
} 
```
然后你按键盘前可以先设置为`true`等做完某些操作再设置回`false`.

**Comment by wangyi7099** [comment]
好的 我要出一个配置项。。 
```javascript
{
  vuescroll: {
    nativeScrollDisable: false
 }
} 
```
然后你按键盘前可以先设置为`true`等做完某些操作再设置回`false`.

**Comment by wangyi7099** [comment]
@bolerole  能说下你是如何监听的上下左右事件吗？ 比较好奇= = 难道是给div加上tabindex吗？
