### ISSUE TITLE
可以把transform改用position来实现滑动

### ISSUE THREAD

**Issue by qweaa** [YvesCoding/vuescroll#95]
使用transform的vuescroll，vuescroll内的元素如果存在position会失效，vuescroll叠加vuescroll出现了两个滚动条
.__panel {
 ...
    position: absolute;
...
}

var transformProperty = 'transform' => var transformProperty = 'top'

**Comment by qweaa** [comment]
或者提供使用position来实现滑动的配置参数

**Comment by wangyi7099** [comment]
会出现2个滚动条？  额。。 能否给出一个重现的demo？
