### ISSUE TITLE
webpack打包后因__vuescroll .__panel.x-hidden{width:100%}样式导致右侧出现两个滚动条

### ISSUE THREAD

**Issue by Rtfsc8** [YvesCoding/vuescroll#96]
dependencies: {
    "vuescroll": "^4.8.12",
}

devDependencies:{
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
}
实际打包时，本地下载的4.8.13版本，上测试服务器下载的4.9.0版本。
在4.9.0版本时，会多出x-hidden样式，导致右侧出现两个滚动条。

**Comment by wangyi7099** [comment]
Fixed in 4.9.1
