### ISSUE TITLE
scrollIntoView doesn't work! Even on the demo codepen!

### ISSUE THREAD

**Issue by ngstwr** [YvesCoding/vuescroll#97]
I banged with my head in frustration trying to figure out why it isn't working on my app, turned out it doesn't work on the codepen demo given on the documentation page.

**Comment by wangyi7099** [comment]
Currentlly, api demo is **outdated**, and it doesn't add `css file`.
` <link rel="stylesheet" href="https://unpkg.com/vuescroll/dist/vuescroll.css">`
`scrollIntoView` only works for the directly child element of `vuescroll`.
